//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.CmsKitManagement.Contents
{
    public partial interface IContentsApi : //auto-generated
        Volo.Abp.Application.Services.IApplicationService,
        IContentDefinitionCrudAppService,
        IContentTypeCrudAppService,
        IEntityContentCrudAppService,
        IEntityContentDefinitionCrudAppService
    {
    }
}
