//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Contents
{
    public partial interface IContentTypeCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.CmsKitManagement.Contents.Dtos.ContentTypeWithDetailsDto, FS.CmsKitManagement.Contents.Dtos.ContentTypePrimaryKeyDto, FS.CmsKitManagement.Contents.Dtos.ContentTypeGetListDto, FS.CmsKitManagement.Contents.Dtos.ContentTypeCreateDto, FS.CmsKitManagement.Contents.Dtos.ContentTypeUpdateDto>
    {

    }
}
