import { DEFAULT_DOCUMENTDEFINITION_CREATE_FORM_PROPS } from './default-documentdefinition-create-form-props';

export const DEFAULT_DOCUMENTDEFINITION_EDIT_FORM_PROPS = DEFAULT_DOCUMENTDEFINITION_CREATE_FORM_PROPS;
