//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.CodingManagement.EntityFrameworkCore
{
    public static partial class CodingManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureCodingManagement(
            this ModelBuilder builder,
            Action<CodingManagementModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new CodingManagementModelBuilderConfigurationOptions(
                CodingManagementDbProperties.DbTablePrefix,
                CodingManagementDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CodingManagement.Codes.Coding>(new FS.CodingManagement.Codes.CodingConfiguration(options));
            builder.ApplyConfiguration<FS.CodingManagement.SerialNumbers.SerialNumber>(new FS.CodingManagement.SerialNumbers.SerialNumberConfiguration(options));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
