//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.Customers.Dtos
{

    public partial class CustomerDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Phone { get; set; }

        public virtual string Email { get; set; }

        public virtual string Discriminator { get; set; }

    }

    public partial class CustomerCreateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual string Phone { get; set; }

        public virtual string Email { get; set; }

        public virtual string Discriminator { get; set; }

    }

    public partial class CustomerUpdateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual string Phone { get; set; }

        public virtual string Email { get; set; }

        public virtual string Discriminator { get; set; }

    }

    public partial class CustomerGetListDto : PagedAndSortedResultRequestDto, FS.Abp.Application.Dtos.IDiscriminatorResultRequest
    {
        public virtual string Discriminator { get; set; }

    }

    public partial class CustomerWithDetailsDto : CustomerDto
    {
    }
}
