//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.3.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace FS.Customers.Dtos
{
    public partial class CustomerJsonSubtypesConverterProfile : FS.Abp.AspNetCore.Mvc.JsonSubTypes.JsonSubtypesConverterProfile
    {
        public CustomerJsonSubtypesConverterProfile()
        {
            this.CreateJsonSubtypesConverter<CustomerDto>("Discriminator")
                .RegisterSubtype<FS.Customers.Dtos.EnterpriseDto>((FS.Customers.CustomerDiscriminator)2)
                .RegisterSubtype<FS.Customers.Dtos.PersonDto>((FS.Customers.CustomerDiscriminator)1)
                ;

            this.CreateJsonSubtypesConverter<CustomerCreateDto>("Discriminator")
                .RegisterSubtype<FS.Customers.Dtos.EnterpriseCreateDto>((FS.Customers.CustomerDiscriminator)2)
                .RegisterSubtype<FS.Customers.Dtos.PersonCreateDto>((FS.Customers.CustomerDiscriminator)1)
                ;

            this.CreateJsonSubtypesConverter<CustomerUpdateDto>("Discriminator")
                .RegisterSubtype<FS.Customers.Dtos.EnterpriseUpdateDto>((FS.Customers.CustomerDiscriminator)2)
                .RegisterSubtype<FS.Customers.Dtos.PersonUpdateDto>((FS.Customers.CustomerDiscriminator)1)
                ;

            this.CreateJsonSubtypesConverter<CustomerWithDetailsDto>("Discriminator")
                .RegisterSubtype<FS.Customers.Dtos.EnterpriseWithDetailsDto>((FS.Customers.CustomerDiscriminator)2)
                .RegisterSubtype<FS.Customers.Dtos.PersonWithDetailsDto>((FS.Customers.CustomerDiscriminator)1)
                ;

        }
    }

}
