//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.Customers
{
    public partial interface ICustomersStore // pls write here
    {
    }
    public partial class CustomersStore : ICustomersStore // pls write here
    {

    } 
}
