//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.FormManagement.EntityFrameworkCore
{
    public static class FormManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureFormManagement(
            this ModelBuilder builder,
            Action<FormManagementModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new FormManagementModelBuilderConfigurationOptions(
                FormManagementDbProperties.DbTablePrefix,
                FormManagementDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

            builder.ApplyConfiguration<FS.FormManagement.Forms.Form>(new FS.FormManagement.Forms.FormConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.Group>(new FS.FormManagement.Forms.GroupConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.Checkbox>(new FS.FormManagement.Forms.CheckboxConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.ChoiceMultiple>(new FS.FormManagement.Forms.ChoiceMultipleConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.DropdownList>(new FS.FormManagement.Forms.DropdownListConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.ShortText>(new FS.FormManagement.Forms.ShortTextConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.Question>(new FS.FormManagement.Forms.QuestionConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Versions.Version>(new FS.FormManagement.Versions.VersionConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.FormResponses.FormResponse>(new FS.FormManagement.FormResponses.FormResponseConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.FormResponses.Answer>(new FS.FormManagement.FormResponses.AnswerConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Versions.VersionDefinition>(new FS.FormManagement.Versions.VersionDefinitionConfiguration(options));
            builder.ApplyConfiguration<FS.FormManagement.Forms.Choice>(new FS.FormManagement.Forms.ChoiceConfiguration(options));
        }
    }
}
