//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
namespace FS.FormManagement.EntityFrameworkCore
{
    [ConnectionStringName(FormManagementDbProperties.ConnectionStringName)]
    public partial class FormManagementDbContext : AbpDbContext<FormManagementDbContext>, IFormManagementDbContext
    {

        public virtual DbSet<FS.FormManagement.Groups.Group> Groups
        {
            get;
            set;
        }

        public virtual DbSet<FS.FormManagement.Groups.GroupQuestion> GroupQuestions
        {
            get;
            set;
        }

        public virtual DbSet<FS.FormManagement.Versions.Version> Versions
        {
            get;
            set;
        }

        public virtual DbSet<FS.FormManagement.Versions.VersionDefinition> VersionDefinitions
        {
            get;
            set;
        }
        public FormManagementDbContext(DbContextOptions<FormManagementDbContext> options) :
            base(options)
        {
            OnCreated();
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ConfigureFormManagement();

            CustomizeMapping(ref builder);

            base.OnModelCreating(builder);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        partial void OnCreated();
    }
}
