//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKitManagement.Routes.Dtos
{
    public partial class RouteAutoMapperProfile : Profile
    {
        public RouteAutoMapperProfile()
        {
            CreateMap<FS.CmsKitManagement.Routes.Route, RouteDto>()
            .ReverseMap();
        
            CreateMap<RouteCreateDto, FS.CmsKitManagement.Routes.Route>();
        
            CreateMap<RouteUpdateDto, FS.CmsKitManagement.Routes.Route>();
        
            CreateMap<FS.CmsKitManagement.Routes.Route, RouteWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
