//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Routes
{
    public partial class RouteDefinitionCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.CmsKitManagement.Routes.RouteDefinition, FS.CmsKitManagement.Routes.Dtos.RouteDefinitionWithDetailsDto, FS.CmsKitManagement.Routes.Dtos.RouteDefinitionPrimaryKeyDto, Guid, FS.CmsKitManagement.Routes.Dtos.RouteDefinitionGetListDto, FS.CmsKitManagement.Routes.Dtos.RouteDefinitionCreateDto, FS.CmsKitManagement.Routes.Dtos.RouteDefinitionUpdateDto>,
        IRouteDefinitionCrudAppService
    {
        private readonly IRouteDefinitionRepository _repository;

        public RouteDefinitionCrudAppService(IRouteDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
