//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FS.Cms.Core
{
    public partial interface ICoreAppService : Volo.Abp.Application.Services.IApplicationService // pls write here
    {
    }
}
