//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.Cms.Documents
{
    public partial interface IDocumentsStore
    {
    }
    public partial class DocumentsStore : IDocumentsStore
    {

    } 
}
