//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.CmsKitManagement.Vocabularies
{
    public class VocabulariesPermissionNames
    {
        public const string ModuleName = "FS.CmsKitManagement.Vocabularies";
        public static class VocabularyDefinition
        {
            public const string Default = ModuleName + ".VocabularyDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class Vocabulary
        {
            public const string Default = ModuleName + ".Vocabulary";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(VocabulariesPermissionNames));
        }
    }
}
