//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;

namespace FS.Cms.Blogs
{
    public partial class EfCoreBlogRepository : 
        EfCoreRepository<FS.Cms.EntityFrameworkCore.ICmsDbContext, FS.Cms.Blogs.Blog, Guid>,
        IBlogRepository
    {
        public EfCoreBlogRepository(IDbContextProvider<FS.Cms.EntityFrameworkCore.ICmsDbContext> dbContextProvider)
            : base(dbContextProvider){}
    }
}
