//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Linq.Expressions;

namespace FS.Cms.Blogs
{
    public partial class EfCoreBlogTreeRepository : 
        EasyAbp.Abp.Trees.EfCoreTreeRepository<FS.Cms.EntityFrameworkCore.ICmsDbContext,FS.Cms.Blogs.Blog>,
        IBlogTreeRepository
    {
        public EfCoreBlogTreeRepository(IDbContextProvider<FS.Cms.EntityFrameworkCore.ICmsDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override IQueryable<FS.Cms.Blogs.Blog> WithDetails()
        {
            return GetQueryable().IncludeDetails();
        }
    }
}
