//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.Cms.Localization;

namespace FS.Cms.Posts
{
    public class PostsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var PostsGroup = context.AddGroup(PostsPermissionNames.ModuleName,L(PostsPermissionNames.ModuleName));

            var Post = PostsGroup.AddPermission(PostsPermissionNames.Post.Default,L(PostsPermissionNames.Post.Default));
            Post.AddChild(PostsPermissionNames.Post.Create , L("DisplayName:Post.Create"));
            Post.AddChild(PostsPermissionNames.Post.Update , L("DisplayName:Post.Update"));
            Post.AddChild(PostsPermissionNames.Post.Delete , L("DisplayName:Post.Delete"));

            var PostTagMap = PostsGroup.AddPermission(PostsPermissionNames.PostTagMap.Default,L(PostsPermissionNames.PostTagMap.Default));
            PostTagMap.AddChild(PostsPermissionNames.PostTagMap.Create , L("DisplayName:PostTagMap.Create"));
            PostTagMap.AddChild(PostsPermissionNames.PostTagMap.Update , L("DisplayName:PostTagMap.Update"));
            PostTagMap.AddChild(PostsPermissionNames.PostTagMap.Delete , L("DisplayName:PostTagMap.Delete"));

        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<CmsResource>(name);
        }
    }
}
