//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Theme.Routes.Dtos
{
    public partial class MyRouteDefinitionCreateDtoValidator : AbstractValidator<MyRouteDefinitionCreateDto>
    {
        public MyRouteDefinitionCreateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class MyRouteDefinitionUpdateDtoValidator : AbstractValidator<MyRouteDefinitionUpdateDto>
    {
        public MyRouteDefinitionUpdateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
