//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Theme.Routes.Dtos
{
    public partial class RouteDefinitionAutoMapperProfile : Profile
    {
        public RouteDefinitionAutoMapperProfile()
        {
            CreateMap<FS.Theme.Routes.RouteDefinition, RouteDefinitionDto>()
            .Include<FS.Theme.Routes.MyRouteDefinition, FS.Theme.Routes.Dtos.MyRouteDefinitionDto>()
            .ReverseMap();
        
            CreateMap<RouteDefinitionCreateDto, FS.Theme.Routes.RouteDefinition>()
            .Include<FS.Theme.Routes.Dtos.MyRouteDefinitionCreateDto, FS.Theme.Routes.MyRouteDefinition>();
        
            CreateMap<RouteDefinitionUpdateDto, FS.Theme.Routes.RouteDefinition>()
            .Include<FS.Theme.Routes.Dtos.MyRouteDefinitionUpdateDto, FS.Theme.Routes.MyRouteDefinition>();
        
            CreateMap<FS.Theme.Routes.RouteDefinition, RouteDefinitionWithDetailsDto>()
            .Include<FS.Theme.Routes.MyRouteDefinition, FS.Theme.Routes.Dtos.MyRouteDefinitionWithDetailsDto>();
        
            
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
