//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.FormManagement.Forms.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.FormManagement.Forms
{
    public partial class FormsApi //: IFormCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("form/id")]
        [NonAction][RemoteService(false)]
        public Task<FormWithDetailsDto> GetAsync([FromQuery] FormPrimaryKeyDto FormPrimaryKey)
        {
            return this.FormCrudAppService.GetAsync(FormPrimaryKey);
        }

        [HttpGet]
        [Route("form")]
        [RemoteService(true)]
        public Task<PagedResultDto<FormWithDetailsDto>> GetListAsync(FormGetListDto FormGetList)
        {
            return this.FormCrudAppService.GetListAsync(FormGetList);
        }

        [HttpPost]
        [Route("form")]
        [NonAction][RemoteService(false)]
        public Task<FormWithDetailsDto> CreateAsync(FormCreateDto FormCreate)
        {
            return this.FormCrudAppService.CreateAsync(FormCreate);
        }

        [HttpPut]
        [Route("form/id")]
        [NonAction][RemoteService(false)]
        public Task<FormWithDetailsDto> UpdateAsync([FromQuery] FormPrimaryKeyDto FormPrimaryKey, FormUpdateDto FormUpdate)
        {
            return this.FormCrudAppService.UpdateAsync(FormPrimaryKey,FormUpdate);
        }

        [HttpDelete]
        [Route("form/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] FormPrimaryKeyDto FormPrimaryKey)
        {
            return this.FormCrudAppService.DeleteAsync(FormPrimaryKey);
        }
    }
}
