//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.3.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Blogs
{
    public partial interface IPostRouteCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.CmsKitManagement.Blogs.Dtos.PostRouteWithDetailsDto, Guid, FS.CmsKitManagement.Blogs.Dtos.PostRouteGetListDto, FS.CmsKitManagement.Blogs.Dtos.PostRouteCreateDto, FS.CmsKitManagement.Blogs.Dtos.PostRouteUpdateDto>
    {

    }
}
