//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 2.0.1
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FS.Cms.Tags
{
    public partial class TagsAppService : CmsAppService, ITagsAppService // pls write here
    {
    }
}
