//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.Theme.EntityFrameworkCore;

namespace FS.Theme.Routes
{
    public partial class RouteDefinitionConfiguration : IEntityTypeConfiguration<RouteDefinition>
    {
        private ThemeModelBuilderConfigurationOptions options;
        public RouteDefinitionConfiguration(ThemeModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<RouteDefinition> builder)
        {
            builder.ToTable(options.TablePrefix + @"RouteDefinitions", options.Schema);
            builder.Property<string>(x => x.No).HasColumnName(@"No").IsRequired().ValueGeneratedNever();
            builder.Property<string>(x => x.DisplayName).HasColumnName(@"DisplayName").IsRequired().ValueGeneratedNever();
            builder.Property<string>(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            builder.Property<bool>(x => x.Enable).HasColumnName(@"Enable").IsRequired().ValueGeneratedNever().HasDefaultValue(true);
            builder.Property<System.Guid?>(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasMany(x => x.Routes).WithOne(op => op.RouteDefinition).IsRequired(true).HasForeignKey(@"RouteDefinitionId");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<RouteDefinition> builder);

        #endregion
    }

}
