//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.Forms.Dtos
{
    public partial class ChoiceAutoMapperProfile : Profile
    {
        public ChoiceAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.Forms.Choice, ChoiceDto>()
            .ReverseMap();
        
            CreateMap<ChoiceCreateDto, FS.FormManagement.Forms.Choice>();
        
            CreateMap<ChoiceUpdateDto, FS.FormManagement.Forms.Choice>();
        
            CreateMap<FS.FormManagement.Forms.Choice, ChoiceWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
