//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.FormManagement.Forms.Dtos
{
    public partial class ChoiceCreateDtoValidator : AbstractValidator<ChoiceCreateDto>
    {
        public ChoiceCreateDtoValidator()
        {
            RuleFor(p => p.No)
                .NotNull()
                ;
            RuleFor(p => p.Sequence)
                .NotNull()
                ;
            RuleFor(p => p.QuestionId)
                .NotNull()
                ;
            RuleFor(p => p.IsCorrect)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ChoiceUpdateDtoValidator : AbstractValidator<ChoiceUpdateDto>
    {
        public ChoiceUpdateDtoValidator()
        {
            RuleFor(p => p.No)
                .NotNull()
                ;
            RuleFor(p => p.Sequence)
                .NotNull()
                ;
            RuleFor(p => p.QuestionId)
                .NotNull()
                ;
            RuleFor(p => p.IsCorrect)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
