//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.Forms.Dtos
{
    public partial class FormalAutoMapperProfile : Profile
    {
        public FormalAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.Forms.Formal, FormalDto>()
            .ReverseMap();
        
            CreateMap<FormalCreateDto, FS.FormManagement.Forms.Formal>();
        
            CreateMap<FormalUpdateDto, FS.FormManagement.Forms.Formal>();
        
            CreateMap<FS.FormManagement.Forms.Formal, FormalWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
