//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.Forms.Dtos
{
    public partial class ItemAutoMapperProfile : Profile
    {
        public ItemAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.Forms.Item, ItemDto>()
            .ReverseMap();
        
            CreateMap<ItemCreateDto, FS.FormManagement.Forms.Item>();
        
            CreateMap<ItemUpdateDto, FS.FormManagement.Forms.Item>();
        
            CreateMap<FS.FormManagement.Forms.Item, ItemWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
