//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.Forms.Dtos
{
    public partial class QuestionAutoMapperProfile : Profile
    {
        public QuestionAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.Forms.Question, QuestionDto>()
            .Include<FS.FormManagement.Forms.Checkbox, FS.FormManagement.Forms.Dtos.CheckboxDto>()
            .Include<FS.FormManagement.Forms.ChoiceMultiple, FS.FormManagement.Forms.Dtos.ChoiceMultipleDto>()
            .Include<FS.FormManagement.Forms.DropdownList, FS.FormManagement.Forms.Dtos.DropdownListDto>()
            .Include<FS.FormManagement.Forms.ShortText, FS.FormManagement.Forms.Dtos.ShortTextDto>()
            .ReverseMap();
        
            CreateMap<QuestionCreateDto, FS.FormManagement.Forms.Question>()
            .Include<FS.FormManagement.Forms.Dtos.CheckboxCreateDto, FS.FormManagement.Forms.Checkbox>()
            .Include<FS.FormManagement.Forms.Dtos.ChoiceMultipleCreateDto, FS.FormManagement.Forms.ChoiceMultiple>()
            .Include<FS.FormManagement.Forms.Dtos.DropdownListCreateDto, FS.FormManagement.Forms.DropdownList>()
            .Include<FS.FormManagement.Forms.Dtos.ShortTextCreateDto, FS.FormManagement.Forms.ShortText>();
        
            CreateMap<QuestionUpdateDto, FS.FormManagement.Forms.Question>()
            .Include<FS.FormManagement.Forms.Dtos.CheckboxUpdateDto, FS.FormManagement.Forms.Checkbox>()
            .Include<FS.FormManagement.Forms.Dtos.ChoiceMultipleUpdateDto, FS.FormManagement.Forms.ChoiceMultiple>()
            .Include<FS.FormManagement.Forms.Dtos.DropdownListUpdateDto, FS.FormManagement.Forms.DropdownList>()
            .Include<FS.FormManagement.Forms.Dtos.ShortTextUpdateDto, FS.FormManagement.Forms.ShortText>();
        
            CreateMap<FS.FormManagement.Forms.Question, QuestionWithDetailsDto>()
            .Include<FS.FormManagement.Forms.Checkbox, FS.FormManagement.Forms.Dtos.CheckboxWithDetailsDto>()
            .Include<FS.FormManagement.Forms.ChoiceMultiple, FS.FormManagement.Forms.Dtos.ChoiceMultipleWithDetailsDto>()
            .Include<FS.FormManagement.Forms.DropdownList, FS.FormManagement.Forms.Dtos.DropdownListWithDetailsDto>()
            .Include<FS.FormManagement.Forms.ShortText, FS.FormManagement.Forms.Dtos.ShortTextWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
