//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.FormManagement.Forms.Dtos
{
    public partial class ShortTextCreateDtoValidator : AbstractValidator<ShortTextCreateDto>
    {
        public ShortTextCreateDtoValidator()
        {
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ShortTextUpdateDtoValidator : AbstractValidator<ShortTextUpdateDto>
    {
        public ShortTextUpdateDtoValidator()
        {
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
