//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.PrinterManagement.Printing.Dtos
{
    public partial class PaperSizeAutoMapperProfile : Profile
    {
        public PaperSizeAutoMapperProfile()
        {
            CreateMap<FS.PrinterManagement.Printing.PaperSize, PaperSizeDto>()
            .ReverseMap();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
