//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Cms.Core.Dtos
{
    public partial class CmsFileFieldAutoMapperProfile : Profile
    {
        public CmsFileFieldAutoMapperProfile()
        {
            CreateMap<FS.Cms.Core.CmsFileField, CmsFileFieldDto>()
            .ReverseMap();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
