//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Cms.Core.Dtos
{
    public partial class 前台參數設定AutoMapperProfile : Profile
    {
        public 前台參數設定AutoMapperProfile()
        {
            CreateMap<FS.Cms.Core.前台參數設定, 前台參數設定Dto>()
            .ReverseMap();
        
            CreateMap<FS.Cms.Core.前台參數設定, 前台參數設定WithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
