//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 420.0.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Abp.Emailing.Dtos
{
    public partial class MetaData
    {
        public SmtpDto SmtpDto => new SmtpDto();
    }

    public partial class SmtpDto
    {
        public virtual string Host { get; set; }

        public virtual int Port { get; set; }

        public virtual string UserName { get; set; }

        public virtual string Password { get; set; }

        public virtual string Domain { get; set; }

        public virtual bool EnableSsl { get; set; }

        public virtual bool UseDefaultCredentials { get; set; }

    }
}
