//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Cms.Blogs.Dtos
{
    public partial class BlogAutoMapperProfile : Profile
    {
        public BlogAutoMapperProfile()
        {
            CreateMap<FS.Cms.Blogs.Blog, BlogDto>()
            .ReverseMap();
        
            CreateMap<BlogCreateDto, FS.Cms.Blogs.Blog>();
        
            CreateMap<BlogUpdateDto, FS.Cms.Blogs.Blog>();
        
            CreateMap<FS.Cms.Blogs.Blog, BlogWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
