//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Theme.WebSites.Dtos
{
    public partial class MetaData
    {
        public WebSiteConfigDto WebSiteConfigDto => new WebSiteConfigDto();
    }

    public partial class WebSiteConfigDto
    {
        public virtual string LogoFileId { get; set; }

        public virtual string Title { get; set; }

        public virtual string Favicon { get; set; }

        public virtual int Count { get; set; }

        public virtual string Copyright { get; set; }

    }
}
