//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Vocabularies
{
    public partial class VocabularyDefinitionCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.CmsKitManagement.Vocabularies.VocabularyDefinition, FS.CmsKitManagement.Vocabularies.Dtos.VocabularyDefinitionWithDetailsDto, FS.CmsKitManagement.Vocabularies.Dtos.VocabularyDefinitionPrimaryKeyDto, Guid, FS.CmsKitManagement.Vocabularies.Dtos.VocabularyDefinitionGetListDto, FS.CmsKitManagement.Vocabularies.Dtos.VocabularyDefinitionCreateDto, FS.CmsKitManagement.Vocabularies.Dtos.VocabularyDefinitionUpdateDto>,
        IVocabularyDefinitionCrudAppService
    {
        private readonly IVocabularyDefinitionRepository _repository;

        public VocabularyDefinitionCrudAppService(IVocabularyDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
