//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CodingManagement.SerialNumbers
{
    public partial class SerialNumberCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.CodingManagement.SerialNumbers.SerialNumber, FS.CodingManagement.SerialNumbers.Dtos.SerialNumberWithDetailsDto, FS.CodingManagement.SerialNumbers.Dtos.SerialNumberPrimaryKeyDto, Guid, FS.CodingManagement.SerialNumbers.Dtos.SerialNumberGetListDto, FS.CodingManagement.SerialNumbers.Dtos.SerialNumberCreateDto, FS.CodingManagement.SerialNumbers.Dtos.SerialNumberUpdateDto>,
        ISerialNumberCrudAppService
    {
        private readonly ISerialNumberRepository _repository;

        public SerialNumberCrudAppService(ISerialNumberRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
