//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Customers
{
    public partial interface ICustomerCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.Customers.Dtos.CustomerWithDetailsDto, Guid, FS.Customers.Dtos.CustomerGetListDto, FS.Customers.Dtos.CustomerCreateDto, FS.Customers.Dtos.CustomerUpdateDto>
    {

    }
}
