//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Cms.Core.Dtos
{
    public partial class MetaData
    {
        public ResourceDto ResourceDto => new ResourceDto();
    }

    public partial class ResourceDto
    {
        public virtual string FileId { get; set; }

        public virtual string No { get; set; }

        public virtual bool Default { get; set; }

        public virtual int Sequence { get; set; }

        public virtual Dictionary<string, string> Properties { get; set; }

    }
}
