//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
//------------------------------------------------------------------------------
using FS.Cms.Blogs.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.Cms.Blogs
{
    public partial class BlogsApi : IBlogCrudAppService //pls write here
    {
        [NonAction]
        [RemoteService(false)]
        public async Task<PagedResultDto<BlogWithDetailsDto>> GetBlogs(GetBlogsInput input, bool isFront = false)
        {
            return await this.BlogCrudAppService.GetBlogs(input);
        }
    }
}
