//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Theme.Routes.Dtos
{
    public partial class RouteConfigDto
    {
        public string Icon { get; set; }

        public string Url { get; set; }

        public int Sequence { get; set; }

        public bool OpenAnotherWindow { get; set; }

    }
    public partial class RouteConfigWithDetailsDto : RouteConfigDto
    {
    }
}
