//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Theme.Routes.Dtos
{
    public partial class RoutePrimaryKeyDto : EntityDto<Guid>
    {
    }
    public partial class RouteDto : Volo.Abp.Application.Dtos.AuditedEntityDto<Guid>
    {
        public string No { get; set; }

        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public int Level { get; set; }

        public System.Guid? ParentId { get; set; }

        public bool Enable { get; set; }

        public FS.Theme.Routes.Dtos.RouteConfigDto RouteConfig { get; set; }

        public System.Guid RouteDefinitionId { get; set; }

    }
    public partial class RouteWithDetailsDto : RouteDto
    {
        public RouteDefinitionDto RouteDefinition { get; set; }

        public List<RouteDto> Children { get; set; }

        public RouteDto Parent { get; set; }

    }
    public partial class RouteCreateDto
    {
        public string No { get; set; }

        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public int Level { get; set; }

        public System.Guid? ParentId { get; set; }

        public bool Enable { get; set; }

        public FS.Theme.Routes.Dtos.RouteConfigDto RouteConfig { get; set; }

        public System.Guid RouteDefinitionId { get; set; }

    }
    public partial class RouteUpdateDto
    {
        public string No { get; set; }

        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public int Level { get; set; }

        public System.Guid? ParentId { get; set; }

        public bool Enable { get; set; }

        public FS.Theme.Routes.Dtos.RouteConfigDto RouteConfig { get; set; }

        public System.Guid RouteDefinitionId { get; set; }

    }
    public partial class RouteGetListDto : SearchResultRequestDto
    {
    }
}
