//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.CmsKitManagement.Contents.Dtos
{
    public partial class EntityContentDefinitionWithDetailsDto : EntityContentDefinitionDto
    {
        public ContentDefinitionWithDetailsDto ContentDefinition { get; set; }
    }
}
