//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 2.0.1
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.Cms.Tags
{
    public partial interface ITagsApi : ITagsAppService // pls write here
    {
    }
}
