//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.Cms.Blogs
{
    public partial interface IBlogsStore : IDomainService //auto-generated
    {
        IBlogTreeRepository Blog { get; }
    }
    public partial class BlogsStore : DomainService //auto-generated
    {
        private IBlogTreeRepository _Blog;
        public IBlogTreeRepository Blog => this.LazyGetRequiredService(ref _Blog);
    }
}
