//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.CmsKitManagement.EntityBlogs
{
    [Area("cms-kit-management")]
    [RemoteService(Name ="cms-kit-management")]
    [ControllerName("FS.CmsKitManagement.EntityBlogs(cms-kit-management)")]
    [Route("api/cms-kit-management/entity-blogs")]
    public partial class EntityBlogsApi : CmsKitManagementController , IEntityBlogsApi //auto-generated
    {

        protected IEntityBlogCrudAppService EntityBlogCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IEntityBlogCrudAppService>();

    }
}
