//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.Groups
{
    public partial class GroupCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.FormManagement.Groups.Group, FS.FormManagement.Groups.Dtos.GroupWithDetailsDto, FS.FormManagement.Groups.Dtos.GroupPrimaryKeyDto, Guid, FS.FormManagement.Groups.Dtos.GroupGetListDto, FS.FormManagement.Groups.Dtos.GroupCreateDto, FS.FormManagement.Groups.Dtos.GroupUpdateDto>,
        IGroupCrudAppService
    {
        private readonly IGroupTreeRepository _repository;

        public GroupCrudAppService(IGroupTreeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
