import { DEFAULT_VERSIONDEFINITION_CREATE_FORM_PROPS } from './default-versiondefinition-create-form-props';

export const DEFAULT_VERSIONDEFINITION_EDIT_FORM_PROPS = DEFAULT_VERSIONDEFINITION_CREATE_FORM_PROPS;
