//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.FormManagement.Documents
{
    public partial interface IDocumentsApi : //auto-generated
        Volo.Abp.Application.Services.IApplicationService,
        IVersionCrudAppService,
        IDocumentDefinitionCrudAppService
    {
    }
}
