//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.Documents
{
    public partial interface IDocumentDefinitionCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.FormManagement.Documents.Dtos.DocumentDefinitionWithDetailsDto, FS.FormManagement.Documents.Dtos.DocumentDefinitionPrimaryKeyDto, FS.FormManagement.Documents.Dtos.DocumentDefinitionGetListDto, FS.FormManagement.Documents.Dtos.DocumentDefinitionCreateDto, FS.FormManagement.Documents.Dtos.DocumentDefinitionUpdateDto>
    {

    }
}
