//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Shapes
{
    public partial class ShapeCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.CmsKitManagement.Shapes.Shape, FS.CmsKitManagement.Shapes.Dtos.ShapeWithDetailsDto, FS.CmsKitManagement.Shapes.Dtos.ShapePrimaryKeyDto, Guid, FS.CmsKitManagement.Shapes.Dtos.ShapeGetListDto, FS.CmsKitManagement.Shapes.Dtos.ShapeCreateDto, FS.CmsKitManagement.Shapes.Dtos.ShapeUpdateDto>,
        IShapeCrudAppService
    {
        private readonly IShapeRepository _repository;

        public ShapeCrudAppService(IShapeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
