//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKitManagement.Contents.Dtos
{
    public partial class ContentDefinitionCreateDtoValidator : AbstractValidator<ContentDefinitionCreateDto>
    {
        public ContentDefinitionCreateDtoValidator()
        {
            RuleFor(p => p.EntityType)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentDefinitionUpdateDtoValidator : AbstractValidator<ContentDefinitionUpdateDto>
    {
        public ContentDefinitionUpdateDtoValidator()
        {
            RuleFor(p => p.EntityType)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
