//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CodingManagement.SerialNumbers.EntityFrameworkCore
{
    public static partial class SerialNumbersDbContextModelCreatingExtensions
    {
        public static void ConfigureSerialNumbers(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CodingManagement.SerialNumbers.SerialNumber>(new FS.CodingManagement.SerialNumbers.EntityFrameworkCore.SerialNumberConfiguration(CodingManagementDbProperties.DbTablePrefix,CodingManagementDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
