//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Contents
{
    public partial class ContentPropertyCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.CmsKitManagement.Contents.ContentProperty, FS.CmsKitManagement.Contents.Dtos.ContentPropertyWithDetailsDto, FS.CmsKitManagement.Contents.Dtos.ContentPropertyPrimaryKeyDto, Guid, FS.CmsKitManagement.Contents.Dtos.ContentPropertyGetListDto, FS.CmsKitManagement.Contents.Dtos.ContentPropertyCreateDto, FS.CmsKitManagement.Contents.Dtos.ContentPropertyUpdateDto>,
        IContentPropertyCrudAppService
    {
        private readonly IContentPropertyRepository _repository;

        public ContentPropertyCrudAppService(IContentPropertyRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
