//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Contents
{
    public partial class EntityContentDefinitionCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<FS.CmsKitManagement.Contents.EntityContentDefinition, FS.CmsKitManagement.Contents.Dtos.EntityContentDefinitionWithDetailsDto, Guid, FS.CmsKitManagement.Contents.Dtos.EntityContentDefinitionGetListDto, FS.CmsKitManagement.Contents.Dtos.EntityContentDefinitionCreateDto, FS.CmsKitManagement.Contents.Dtos.EntityContentDefinitionUpdateDto>,
        IEntityContentDefinitionCrudAppService
    {
        private readonly IEntityContentDefinitionRepository _repository;

        public EntityContentDefinitionCrudAppService(IEntityContentDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
