//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.FormManagement.Forms
{
    public partial interface IFormsStore : IDomainService //auto-generated
    {
        IFormRepository Form { get; }
        IGroupTreeRepository Group { get; }
        IQuestionRepository Question { get; }
        IChoiceRepository Choice { get; }
    }
    public partial class FormsStore : DomainService, IFormsStore //auto-generated
    {
        public IFormRepository Form => this.LazyServiceProvider.LazyGetRequiredService<IFormRepository>();
        public IGroupTreeRepository Group => this.LazyServiceProvider.LazyGetRequiredService<IGroupTreeRepository>();
        public IQuestionRepository Question => this.LazyServiceProvider.LazyGetRequiredService<IQuestionRepository>();
        public IChoiceRepository Choice => this.LazyServiceProvider.LazyGetRequiredService<IChoiceRepository>();
    }
}
