//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.FormManagement.Forms
{
    public partial interface IChoiceMultipleRepository : 
        Volo.Abp.Domain.Repositories.IRepository<FS.FormManagement.Forms.ChoiceMultiple,Guid>
    {

    }
}
