//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Cms.Blogs
{
    public partial class BlogCrudAppService : 
        FS.Abp.Application.Services.CrudAppService<FS.Cms.Blogs.Blog, FS.Cms.Blogs.Dtos.BlogDto, Guid, FS.Cms.Blogs.Dtos.BlogGetListInput, FS.Cms.Blogs.Dtos.BlogCreateInput, FS.Cms.Blogs.Dtos.BlogUpdateInput>,
        IBlogCrudAppService
    {
        private readonly IBlogRepository _repository;

        public BlogCrudAppService(IBlogRepository repository) : base(repository)
        {
            this._repository = repository;
        }



    }
}
