//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Theme.Routes
{
    public partial interface IMyRouteDefinitionCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.Theme.Routes.Dtos.MyRouteDefinitionWithDetailsDto, FS.Theme.Routes.Dtos.MyRouteDefinitionPrimaryKeyDto, FS.Theme.Routes.Dtos.MyRouteDefinitionGetListDto, FS.Theme.Routes.Dtos.MyRouteDefinitionCreateDto, FS.Theme.Routes.Dtos.MyRouteDefinitionUpdateDto>
    {

    }
}
