//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Theme.Routes
{
    public partial interface IRouteDefinitionCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.Theme.Routes.Dtos.RouteDefinitionWithDetailsDto, FS.Theme.Routes.Dtos.RouteDefinitionPrimaryKeyDto, FS.Theme.Routes.Dtos.RouteDefinitionGetListDto, FS.Theme.Routes.Dtos.RouteDefinitionCreateDto, FS.Theme.Routes.Dtos.RouteDefinitionUpdateDto>
    {

    }
}
