//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.Theme.Routes
{
    public class RoutesPermissionNames
    {
        public const string GroupName = "FS.Theme.Routes";

        public static class 基本設定
        {
            public const string Default = GroupName + ".基本設定";
            public const string Banners = Default + ".Banners";
            public const string Routes = Default + ".Routes";
        }

        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(RoutesPermissionNames));
        }
    }
}
