//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.Theme.Routes
{
    public class RoutesPermissionNames
    {
        public const string ModuleName = "FS.Theme.Routes";
        public static class RouteDefinition
        {
            public const string Default = ModuleName + ".RouteDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class Route
        {
            public const string Default = ModuleName + ".Route";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(RoutesPermissionNames));
        }
    }
}
