//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.Cms.Posts.Dtos
{
    public partial class PostDto : 
        Volo.Abp.Application.Dtos.FullAuditedEntityDto<Guid>
    {

        #region Properties

        public string Url { get; set; }

        public string CoverImage { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public int ReadCount { get; set; }

        public System.Guid BlogId { get; set; }

        #endregion
        #region GenPropertyTypeDtos
        #endregion 
    }
    public partial class PostWithDetailsDto : PostDto
    {

        #region Navigation Properties

        public FS.Cms.Blogs.Dtos.BlogDto Blog { get; set; }

        #endregion
        
    }
    public partial class PostCreateInput
    {

        #region Properties

        public string Url { get; set; }

        public string CoverImage { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public int ReadCount { get; set; }

        public System.Guid BlogId { get; set; }

        #endregion
        #region GenPropertyTypeDtos
        #endregion 
    }
    public partial class PostUpdateInput
    {

        #region Properties

        public string Url { get; set; }

        public string CoverImage { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public int ReadCount { get; set; }

        public System.Guid BlogId { get; set; }

        #endregion
        #region GenPropertyTypeDtos
        #endregion 
    }
    public partial class PostGetListInput : PagedAndSortedResultRequestDto
    {
    }

}
