//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.FormManagement.Versions.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.FormManagement.Versions
{
    public partial class VersionsApi //: IVersionDefinitionCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("version-definition/id")]
        [NonAction][RemoteService(false)]
        public Task<VersionDefinitionWithDetailsDto> GetAsync([FromQuery] VersionDefinitionPrimaryKeyDto VersionDefinitionPrimaryKey)
        {
            return this.VersionDefinitionCrudAppService.GetAsync(VersionDefinitionPrimaryKey);
        }

        [HttpGet]
        [Route("version-definition")]
        [RemoteService(true)]
        public Task<PagedResultDto<VersionDefinitionWithDetailsDto>> GetListAsync(VersionDefinitionGetListDto VersionDefinitionGetList)
        {
            return this.VersionDefinitionCrudAppService.GetListAsync(VersionDefinitionGetList);
        }

        [HttpPost]
        [Route("version-definition")]
        [NonAction][RemoteService(false)]
        public Task<VersionDefinitionWithDetailsDto> CreateAsync(VersionDefinitionCreateDto VersionDefinitionCreate)
        {
            return this.VersionDefinitionCrudAppService.CreateAsync(VersionDefinitionCreate);
        }

        [HttpPut]
        [Route("version-definition/id")]
        [NonAction][RemoteService(false)]
        public Task<VersionDefinitionWithDetailsDto> UpdateAsync([FromQuery] VersionDefinitionPrimaryKeyDto VersionDefinitionPrimaryKey, VersionDefinitionUpdateDto VersionDefinitionUpdate)
        {
            return this.VersionDefinitionCrudAppService.UpdateAsync(VersionDefinitionPrimaryKey,VersionDefinitionUpdate);
        }

        [HttpDelete]
        [Route("version-definition/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] VersionDefinitionPrimaryKeyDto VersionDefinitionPrimaryKey)
        {
            return this.VersionDefinitionCrudAppService.DeleteAsync(VersionDefinitionPrimaryKey);
        }
    }
}
