//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace FS.CmsKitManagement.Contents
{
    public static class ContentsQueryableExtensions //auto-generated
    {
        public static IQueryable<ContentDefinition> IncludeDetails(this IQueryable<ContentDefinition> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.ContentTypes);
        }
        public static IQueryable<ContentType> IncludeDetails(this IQueryable<ContentType> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.ContentDefinition);
        }
    }
}
