//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.3.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Data;

namespace FS.CmsKitManagement.Vocabularies
{
    public partial class Vocabulary : 
        Volo.Abp.Domain.Entities.Auditing.AuditedAggregateRoot<Guid>,
        Volo.Abp.MultiTenancy.IMultiTenant,
        EasyAbp.Abp.Trees.ITree<Vocabulary>
    {

        public Vocabulary()
        {
            this.Children = new List<Vocabulary>();
            OnCreated();
        }

        public virtual System.Guid VocabularyDefinitionId
        {
            get;
            set;
        }

        public virtual string Code
        {
            get;
            set;
        }

        public virtual System.Guid? ParentId
        {
            get;
            set;
        }

        public virtual int Level
        {
            get;
            set;
        }

        public virtual string DisplayName
        {
            get;
            set;
        }

        /// <summary>
        /// No
        /// </summary>
        public virtual string No
        {
            get;
            set;
        }

        public virtual System.Guid? TenantId
        {
            get;
            set;
        }

        public virtual VocabularyDefinition VocabularyDefinition
        {
            get;
            set;
        }

        public virtual ICollection<Vocabulary> Children
        {
            get;
            set;
        }

        public virtual Vocabulary Parent
        {
            get;
            set;
        }


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
