//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 2.0.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Cms.Posts.Dtos
{
    public partial class PostCreateDtoValidator : AbstractValidator<PostCreateDto>
    {
        public PostCreateDtoValidator()
        {
            RuleFor(p => p.BlogCodeId)
                .NotNull()
                ;
            RuleFor(p => p.Title)
                .NotNull()
                ;
            RuleFor(p => p.Subtitle)
                ;
            RuleFor(p => p.Url)
                ;
            RuleFor(p => p.Content)
                ;
            RuleFor(p => p.Published)
                .NotNull()
                ;
            RuleFor(p => p.Published_By)
                ;
            RuleFor(p => p.Published_At)
                .NotNull()
                ;
            RuleFor(p => p.DisplayMode)
                .NotNull()
                ;
            RuleFor(p => p.Sequence)
                .NotNull()
                ;
            RuleFor(p => p.AttachmentFileUrls)
                .NotNull()
                ;
            RuleFor(p => p.PostImages)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class PostUpdateDtoValidator : AbstractValidator<PostUpdateDto>
    {
        public PostUpdateDtoValidator()
        {
            RuleFor(p => p.BlogCodeId)
                .NotNull()
                ;
            RuleFor(p => p.Title)
                .NotNull()
                ;
            RuleFor(p => p.Subtitle)
                ;
            RuleFor(p => p.Url)
                ;
            RuleFor(p => p.Content)
                ;
            RuleFor(p => p.Published)
                .NotNull()
                ;
            RuleFor(p => p.Published_By)
                ;
            RuleFor(p => p.Published_At)
                .NotNull()
                ;
            RuleFor(p => p.DisplayMode)
                .NotNull()
                ;
            RuleFor(p => p.Sequence)
                .NotNull()
                ;
            RuleFor(p => p.AttachmentFileUrls)
                .NotNull()
                ;
            RuleFor(p => p.PostImages)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
