//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.FormManagement.Documents.Dtos
{
    public partial class MetaData
    {
        public VersionPrimaryKeyDto VersionPrimaryKeyDto => new VersionPrimaryKeyDto();
        public VersionDto VersionDto => new VersionDto();
        public VersionCreateDto VersionCreateDto => new VersionCreateDto();
        public VersionUpdateDto VersionUpdateDto => new VersionUpdateDto();
        public VersionGetListDto VersionGetListDto => new VersionGetListDto();
        public VersionWithDetailsDto VersionWithDetailsDto => new VersionWithDetailsDto();
    }

    public partial class VersionPrimaryKeyDto : EntityDto<Guid>
    {
    }

    public partial class VersionDto : Volo.Abp.Application.Dtos.AuditedEntityDto<Guid>
    {
        public virtual string No { get; set; }

        public virtual System.Guid? PrevVersionId { get; set; }

        public virtual System.Guid? NextVersionId { get; set; }

        public virtual System.Guid DocumentDefinitionId { get; set; }

    }

    public partial class VersionCreateDto
    {
        public virtual string No { get; set; }

        public virtual System.Guid? PrevVersionId { get; set; }

        public virtual System.Guid? NextVersionId { get; set; }

        public virtual System.Guid DocumentDefinitionId { get; set; }

    }

    public partial class VersionUpdateDto
    {
        public virtual string No { get; set; }

        public virtual System.Guid? PrevVersionId { get; set; }

        public virtual System.Guid? NextVersionId { get; set; }

        public virtual System.Guid DocumentDefinitionId { get; set; }

    }

    public partial class VersionGetListDto : SearchResultRequestDto
    {
    }

    public partial class VersionWithDetailsDto : VersionDto
    {
        public DocumentDefinitionDto DocumentDefinition { get; set; }

    }
}
