//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Cms.Posts.Dtos
{
    public partial class PostAutoMapperProfile : Profile
    {
        public PostAutoMapperProfile()
        {
            CreateMap<FS.Cms.Posts.Post, FS.Cms.Posts.Dtos.PostDto>();
            CreateMap<FS.Cms.Posts.Dtos.PostDto, FS.Cms.Posts.Post>().IgnoreAllNonExisting();
            CreateMap<FS.Cms.Posts.Post, FS.Cms.Posts.Dtos.PostWithDetailsDto>();
            CreateMap<FS.Cms.Posts.Dtos.PostCreateInput, FS.Cms.Posts.Post>().IgnoreAllNonExisting();
            CreateMap<FS.Cms.Posts.Dtos.PostUpdateInput, FS.Cms.Posts.Post>().IgnoreAllNonExisting();        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
