//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;

namespace FS.Theme.WebSites
{
    public partial class EfCoreWebSiteDefinitionRepository : 
        EfCoreRepository<FS.Theme.EntityFrameworkCore.IThemeDbContext,FS.Theme.WebSites.WebSiteDefinition,Guid>,
        IWebSiteDefinitionRepository
    {
        public EfCoreWebSiteDefinitionRepository(IDbContextProvider<FS.Theme.EntityFrameworkCore.IThemeDbContext> dbContextProvider)
            : base(dbContextProvider) { }
    }
}
