//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.Theme.EntityFrameworkCore;

namespace FS.Theme.WebSites
{
    public partial class WebSiteDefinitionConfiguration : IEntityTypeConfiguration<WebSiteDefinition>
    {
        private ThemeModelBuilderConfigurationOptions options;
        public WebSiteDefinitionConfiguration(ThemeModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<WebSiteDefinition> builder)
        {
            builder.ToTable(options.TablePrefix + @"WebSiteDefinitions", options.Schema);
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.No).HasColumnName(@"No").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DisplayName).HasColumnName(@"DisplayName").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"Description").ValueGeneratedNever();
            builder.Property(x => x.LogoFileId).HasColumnName(@"LogoFileId").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Title).HasColumnName(@"Title").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.FaviconFileId).HasColumnName(@"FaviconFileId").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Count).HasColumnName(@"Count").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Copyright).HasColumnName(@"Copyright").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.HasKey(@"Id");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<WebSiteDefinition> builder);

        #endregion
    }

}
