//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.CmsKitManagement.MultiLinguals
{
    public partial class MultiLingualsStore : DomainService, IMultiLingualsStore //auto-generated
    {
        public IMultiLingualRepository MultiLingual => this.LazyServiceProvider.LazyGetRequiredService<IMultiLingualRepository>();
        public IMultiLingualTranslationRepository MultiLingualTranslation => this.LazyServiceProvider.LazyGetRequiredService<IMultiLingualTranslationRepository>();
    }
}
