//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace FS.CmsKitManagement.MultiLinguals
{
    public static class MultiLingualsQueryableExtensions //auto-generated
    {
        public static IQueryable<MultiLingual> IncludeDetails(this IQueryable<MultiLingual> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.MultiLingualTranslations);
        }
        public static IQueryable<MultiLingualTranslation> IncludeDetails(this IQueryable<MultiLingualTranslation> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.MultiLingual);
        }
    }
}
