//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.FormResponses
{
    public partial interface IAnswerCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.FormManagement.FormResponses.Dtos.AnswerWithDetailsDto, FS.FormManagement.FormResponses.Dtos.AnswerPrimaryKeyDto, FS.FormManagement.FormResponses.Dtos.AnswerGetListDto, FS.FormManagement.FormResponses.Dtos.AnswerCreateDto, FS.FormManagement.FormResponses.Dtos.AnswerUpdateDto>
    {

    }
}
