//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.Wbm.EntityFrameworkCore;

namespace FS.Wbm.Core
{
    public partial class 過磅Configuration : IEntityTypeConfiguration<過磅>
    {
        private WbmModelBuilderConfigurationOptions options;
        public 過磅Configuration(WbmModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<過磅> builder)
        {
            builder.ToTable(options.TablePrefix + @"過磅", options.Schema);
            builder.Property<long>(@"Id").HasColumnName(@"識別碼").HasColumnType(@"bigint").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.序號).HasColumnName(@"序號").HasColumnType(@"nvarchar(6)").IsRequired().ValueGeneratedNever().HasMaxLength(6);
            builder.Property(x => x.區隊代號).HasColumnName(@"區隊代號").HasColumnType(@"nvarchar(5)").ValueGeneratedNever().HasMaxLength(5);
            builder.Property(x => x.廠商代號).HasColumnName(@"廠商代號").HasColumnType(@"nvarchar(5)").ValueGeneratedNever().HasMaxLength(5);
            builder.Property(x => x.磁卡號碼).HasColumnName(@"磁卡號碼").HasColumnType(@"nvarchar(4)").ValueGeneratedNever().HasMaxLength(4);
            builder.Property(x => x.出廠磅台).HasColumnName(@"出廠磅台").HasColumnType(@"nvarchar(1)").IsRequired().ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.出廠時間).HasColumnName(@"出廠時間").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.過磅代號).HasColumnName(@"過磅代號").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.車牌號碼).HasColumnName(@"車牌號碼").HasColumnType(@"nvarchar(8)").IsRequired().ValueGeneratedNever().HasMaxLength(8);
            builder.Property(x => x.過磅空重).HasColumnName(@"過磅空重").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.過磅總重).HasColumnName(@"過磅總重").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.過磅淨重).HasColumnName(@"過磅淨重").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.料品).HasColumnName(@"料品").HasColumnType(@"nvarchar(2)").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            builder.Property(x => x.料品屬性).HasColumnName(@"料品屬性").HasColumnType(@"nvarchar(8)").ValueGeneratedNever().HasMaxLength(8);
            builder.Property(x => x.金額).HasColumnName(@"金額").HasColumnType(@"real").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.出廠日期).HasColumnName(@"出廠日期").HasColumnType(@"datetime").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.員工編號).HasColumnName(@"員工編號").HasColumnType(@"nvarchar(5)").ValueGeneratedNever().HasMaxLength(5);
            builder.Property(x => x.單價).HasColumnName(@"單價").HasColumnType(@"money").ValueGeneratedNever();
            builder.Property(x => x.規定載重).HasColumnName(@"規定載重").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.滿載率).HasColumnName(@"滿載率").HasColumnType(@"real").ValueGeneratedNever();
            builder.Property(x => x.等級).HasColumnName(@"等級").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.區隊往返).HasColumnName(@"區隊往返").HasColumnType(@"smallint").ValueGeneratedNever();
            builder.Property(x => x.刪除代號).HasColumnName(@"刪除代號").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.高銀).HasColumnName(@"高銀").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.交易序號).HasColumnName(@"交易序號").HasColumnType(@"nvarchar(10)").ValueGeneratedNever().HasMaxLength(10);
            builder.Property(x => x.付款方式).HasColumnName(@"付款方式").HasColumnType(@"nvarchar(3)").ValueGeneratedNever().HasMaxLength(3);
            builder.Property(x => x.單機過磅).HasColumnName(@"單機過磅").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.單機傳送).HasColumnName(@"單機傳送").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.入廠磅台).HasColumnName(@"入廠磅台").HasColumnType(@"nvarchar(1)").ValueGeneratedNever().HasMaxLength(1);
            builder.Property(x => x.收據流水號).HasColumnName(@"收據流水號").HasColumnType(@"nvarchar(7)").ValueGeneratedNever().HasMaxLength(7);
            builder.HasKey(@"Id");

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<過磅> builder);

        #endregion
    }

}
