//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.Cms.Tags
{
    [Area("cms")]
    [RemoteService(true)]
    [ControllerName("FS.Cms.Tags(cms)")]
    [Route("api/cms/tags")]
    public partial class TagsApi : CmsController , ITagsApi //auto-generated
    {

        protected ITagCrudAppService TagCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<ITagCrudAppService>();

        [HttpOptions]
        public Dtos.MetaData Options()
        {
            return new Dtos.MetaData();
        }
    }
}
