//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.Theme.Tenants
{
    [Area("theme")]
    [RemoteService(true)]
    [ControllerName("FS.Theme.Tenants(theme)")]
    [Route("api/theme/tenants")]
    public partial class TenantsApi : ThemeController , ITenantsApi //auto-generated
    {

        protected IThemeSettingsAppService ThemeSettingsAppService => this.LazyServiceProvider.LazyGetRequiredService<IThemeSettingsAppService>();

        [HttpOptions]
        public Dtos.MetaData Options()
        {
            return new Dtos.MetaData();
        }
    }
}
