//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace FS.CodingManagement.Codes
{
    public partial class EfCoreCodingTreeRepository : 
        EasyAbp.Abp.Trees.EfCoreTreeRepository<FS.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext,FS.CodingManagement.Codes.Coding>,
        ICodingTreeRepository
    {
        public async Task<Coding> FindByNoAsync(string no)
        {
            var query = (await this.GetQueryableAsync()).Where(x => x.No == no);
            var result = await query.SingleOrDefaultAsync();
            return result;
        }
    }
}
