//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;

namespace FS.Cms.Blogs
{
    [Area("cms")]
    [RemoteService(true)]
    [ControllerName("FS.Cms.Blogs(cms)")]
    [Route("api/cms/blogs")]
    public partial class BlogsApi : CmsController //auto-generated IBlogsApi
    {
        IBlogsAppService _BlogsAppService;
        protected IBlogsAppService BlogsAppService => this.LazyGetRequiredService(ref _BlogsAppService);

        IBlogCrudAppService _BlogCrudAppService;
        protected IBlogCrudAppService BlogCrudAppService => this.LazyGetRequiredService(ref _BlogCrudAppService);


    }
}
