//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.Cms.EntityFrameworkCore;

namespace FS.Cms.Documents
{
    public partial class DocumentDefinitionConfiguration : IEntityTypeConfiguration<DocumentDefinition>
    {
        private CmsModelBuilderConfigurationOptions options;
        public DocumentDefinitionConfiguration(CmsModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<DocumentDefinition> builder)
        {
            builder.ToTable(options.TablePrefix + @"DocumentDefinitions", options.Schema);
            builder.Property<string>(@"Id").HasColumnName(@"Id").IsRequired().ValueGeneratedNever();
            builder.Ignore(x => x.Images);
            builder.Property(x => x.Title).HasColumnName(@"Title").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Url).HasColumnName(@"Url").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.HasKey(@"Id");

            builder.ConfigureFullAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<DocumentDefinition> builder);

        #endregion
    }

}
