//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.FormManagement.Localization;

namespace FS.FormManagement.Forms
{
    public class FormsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var FormsGroup = context.AddGroup(FormsPermissionNames.ModuleName,L(FormsPermissionNames.ModuleName));

            var Formal = FormsGroup.AddPermission(FormsPermissionNames.Formal.Default,L(FormsPermissionNames.Formal.Default));
            Formal.AddChild(FormsPermissionNames.Formal.Create , L("DisplayName:Formal.Create"));
            Formal.AddChild(FormsPermissionNames.Formal.Update , L("DisplayName:Formal.Update"));
            Formal.AddChild(FormsPermissionNames.Formal.Delete , L("DisplayName:Formal.Delete"));

            var Group = FormsGroup.AddPermission(FormsPermissionNames.Group.Default,L(FormsPermissionNames.Group.Default));
            Group.AddChild(FormsPermissionNames.Group.Create , L("DisplayName:Group.Create"));
            Group.AddChild(FormsPermissionNames.Group.Update , L("DisplayName:Group.Update"));
            Group.AddChild(FormsPermissionNames.Group.Delete , L("DisplayName:Group.Delete"));

            var Item = FormsGroup.AddPermission(FormsPermissionNames.Item.Default,L(FormsPermissionNames.Item.Default));
            Item.AddChild(FormsPermissionNames.Item.Create , L("DisplayName:Item.Create"));
            Item.AddChild(FormsPermissionNames.Item.Update , L("DisplayName:Item.Update"));
            Item.AddChild(FormsPermissionNames.Item.Delete , L("DisplayName:Item.Delete"));

        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<FormManagementResource>(name);
        }
    }
}
