//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.FormManagement.Forms
{
    public class FormsPermissionNames
    {
        public const string ModuleName = "FS.FormManagement.Forms";
        public static class Form
        {
            public const string Default = ModuleName + ".Form";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class Group
        {
            public const string Default = ModuleName + ".Group";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class Checkbox
        {
            public const string Default = ModuleName + ".Checkbox";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ChoiceMultiple
        {
            public const string Default = ModuleName + ".ChoiceMultiple";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class DropdownList
        {
            public const string Default = ModuleName + ".DropdownList";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ShortText
        {
            public const string Default = ModuleName + ".ShortText";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class Question
        {
            public const string Default = ModuleName + ".Question";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class Choice
        {
            public const string Default = ModuleName + ".Choice";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(FormsPermissionNames));
        }
    }
}
