//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.Forms
{
    public partial interface IFormalCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.FormManagement.Forms.Dtos.FormalWithDetailsDto, FS.FormManagement.Forms.Dtos.FormalPrimaryKeyDto, FS.FormManagement.Forms.Dtos.FormalGetListDto, FS.FormManagement.Forms.Dtos.FormalCreateDto, FS.FormManagement.Forms.Dtos.FormalUpdateDto>
    {

    }
}
