//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.PrinterManagement.Printing.Dtos
{

    public partial class MarginsDto
    {
        public virtual int Bottom { get; set; }

        public virtual int Left { get; set; }

        public virtual int Right { get; set; }

        public virtual int Top { get; set; }

    }
}
