//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Cms.Documents
{
    public partial class DocumentCrudAppService : 
        FS.Abp.Application.Services.CrudAppService<FS.Cms.Documents.Document, FS.Cms.Documents.Dtos.DocumentWithDetailsDto, Guid, FS.Cms.Documents.Dtos.DocumentGetListDto, FS.Cms.Documents.Dtos.DocumentCreateDto, FS.Cms.Documents.Dtos.DocumentUpdateDto>,
        IDocumentCrudAppService
    {
        private readonly IDocumentTreeRepository _repository;

        public DocumentCrudAppService(IDocumentTreeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
