//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.CmsKitManagement.Shapes.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKitManagement.Shapes
{
    public partial class ShapesApi //: IShapeCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("shape/id")]
        [NonAction][RemoteService(false)]
        public Task<ShapeWithDetailsDto> GetAsync([FromQuery] ShapePrimaryKeyDto ShapePrimaryKey)
        {
            return this.ShapeCrudAppService.GetAsync(ShapePrimaryKey);
        }

        [HttpGet]
        [Route("shape")]
        [RemoteService(true)]
        public Task<PagedResultDto<ShapeWithDetailsDto>> GetListAsync(ShapeGetListDto ShapeGetList)
        {
            return this.ShapeCrudAppService.GetListAsync(ShapeGetList);
        }

        [HttpPost]
        [Route("shape")]
        [NonAction][RemoteService(false)]
        public Task<ShapeWithDetailsDto> CreateAsync(ShapeCreateDto ShapeCreate)
        {
            return this.ShapeCrudAppService.CreateAsync(ShapeCreate);
        }

        [HttpPut]
        [Route("shape/id")]
        [NonAction][RemoteService(false)]
        public Task<ShapeWithDetailsDto> UpdateAsync([FromQuery] ShapePrimaryKeyDto ShapePrimaryKey, ShapeUpdateDto ShapeUpdate)
        {
            return this.ShapeCrudAppService.UpdateAsync(ShapePrimaryKey,ShapeUpdate);
        }

        [HttpDelete]
        [Route("shape/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] ShapePrimaryKeyDto ShapePrimaryKey)
        {
            return this.ShapeCrudAppService.DeleteAsync(ShapePrimaryKey);
        }
    }
}
