//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Settings.Dtos
{
    public partial class DemoSettingsAutoMapperProfile : Profile
    {
        public DemoSettingsAutoMapperProfile()
        {
            CreateMap<FS.Settings.DemoSettings, DemoSettingsDto>()
            .ReverseMap();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
