//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Cms.Posts.Dtos
{
    public partial class MetaData
    {
        public PostPrimaryKeyDto PostPrimaryKeyDto => new PostPrimaryKeyDto();
        public PostDto PostDto => new PostDto();
        public PostCreateDto PostCreateDto => new PostCreateDto();
        public PostUpdateDto PostUpdateDto => new PostUpdateDto();
        public PostGetListDto PostGetListDto => new PostGetListDto();
        public PostWithDetailsDto PostWithDetailsDto => new PostWithDetailsDto();
    }

    public partial class PostPrimaryKeyDto : EntityDto<Guid>
    {
    }

    public partial class PostDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual System.Guid BlogId { get; set; }

        public virtual string Title { get; set; }

        public virtual string Subtitle { get; set; }

        public virtual int Sequence { get; set; }

        public virtual string LinkUrl { get; set; }

        public virtual bool Disable { get; set; }

        public virtual System.DateTime StartTime { get; set; }

        public virtual System.DateTime? EndTime { get; set; }

        public virtual FS.Cms.Posts.DisplayMode DisplayMode { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Contents { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Attachments { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Images { get; set; }

    }

    public partial class PostCreateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual System.Guid BlogId { get; set; }

        public virtual string Title { get; set; }

        public virtual string Subtitle { get; set; }

        public virtual int Sequence { get; set; }

        public virtual string LinkUrl { get; set; }

        public virtual bool Disable { get; set; }

        public virtual System.DateTime StartTime { get; set; }

        public virtual System.DateTime? EndTime { get; set; }

        public virtual FS.Cms.Posts.DisplayMode DisplayMode { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Contents { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Attachments { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Images { get; set; }

    }

    public partial class PostUpdateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual System.Guid BlogId { get; set; }

        public virtual string Title { get; set; }

        public virtual string Subtitle { get; set; }

        public virtual int Sequence { get; set; }

        public virtual string LinkUrl { get; set; }

        public virtual bool Disable { get; set; }

        public virtual System.DateTime StartTime { get; set; }

        public virtual System.DateTime? EndTime { get; set; }

        public virtual FS.Cms.Posts.DisplayMode DisplayMode { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Contents { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Attachments { get; set; }

        public virtual List<FS.Cms.Core.Dtos.ResourceDto> Images { get; set; }

    }

    public partial class PostGetListDto : SearchResultRequestDto
    {
    }

    public partial class PostWithDetailsDto : PostDto
    {
        public List<PostTagMapDto> PostTags { get; set; }

    }
}
