//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.EntityBlogs
{
    public partial interface IEntityBlogCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.CmsKitManagement.EntityBlogs.Dtos.EntityBlogWithDetailsDto, FS.CmsKitManagement.EntityBlogs.Dtos.EntityBlogPrimaryKeyDto, FS.CmsKitManagement.EntityBlogs.Dtos.EntityBlogGetListDto, FS.CmsKitManagement.EntityBlogs.Dtos.EntityBlogCreateDto, FS.CmsKitManagement.EntityBlogs.Dtos.EntityBlogUpdateDto>
    {

    }
}
