//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.Cms.Posts
{
    public partial interface IPostCrudAppService
    {
    }
}
