//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Cms.Blogs.Dtos
{
    public partial class BlogCreateInputValidator : AbstractValidator<BlogCreateInput>
    {
        public BlogCreateInputValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.ShortName)
                .NotNull()
                ;
            RuleFor(p => p.Description)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class BlogUpdateInputValidator : AbstractValidator<BlogUpdateInput>
    {
        public BlogUpdateInputValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.ShortName)
                .NotNull()
                ;
            RuleFor(p => p.Description)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
