//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.FormManagement.Documents
{
    public partial interface IDocumentsStore : IDomainService //auto-generated
    {
        IVersionRepository Version { get; }
        IDocumentDefinitionRepository DocumentDefinition { get; }
    }
    public partial class DocumentsStore : DomainService, IDocumentsStore //auto-generated
    {
        public IVersionRepository Version => this.LazyServiceProvider.LazyGetRequiredService<IVersionRepository>();
        public IDocumentDefinitionRepository DocumentDefinition => this.LazyServiceProvider.LazyGetRequiredService<IDocumentDefinitionRepository>();
    }
}
