//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.4.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.EntityFrameworkCore
{
    public static partial class FSDbContextModelCreatingExtensions
    {
        public static void ConfigureFS(
            this ModelBuilder builder,
            Action<FSModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new FSModelBuilderConfigurationOptions(
                FSDbProperties.DbTablePrefix,
                FSDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

            CustomizeMapping(ref builder);

            builder.Ignore<FS.Settings.DemoSettings>();
            builder.ApplyConfiguration<FS.Customers.Person>(new FS.Customers.PersonConfiguration(options));
            builder.ApplyConfiguration<FS.Customers.Company>(new FS.Customers.CompanyConfiguration(options));
            builder.ApplyConfiguration<FS.Customers.Customer>(new FS.Customers.CustomerConfiguration(options));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
