//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Customers.Dtos
{
    public partial class CompanyAutoMapperProfile : Profile
    {
        public CompanyAutoMapperProfile()
        {
            CreateMap<FS.Customers.Company, CompanyDto>()
            .ReverseMap();
        
            CreateMap<CompanyCreateDto, FS.Customers.Company>();
        
            CreateMap<CompanyUpdateDto, FS.Customers.Company>();
        
            CreateMap<FS.Customers.Company, CompanyWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
