//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace FS.FormManagement.Forms
{
    public static class FormsQueryableExtensions //auto-generated
    {
        public static IQueryable<Formal> IncludeDetails(this IQueryable<Formal> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.Groups);
        }
        public static IQueryable<Group> IncludeDetails(this IQueryable<Group> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.Children)
                .Include(x => x.Parent)
                .Include(x => x.Formal)
                .Include(x => x.Items);
        }
        public static IQueryable<Item> IncludeDetails(this IQueryable<Item> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.Group);
        }
    }
}
