//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.FormManagement.EntityFrameworkCore;

namespace FS.FormManagement.Forms
{
    public partial class ShortTextConfiguration : IEntityTypeConfiguration<ShortText>
    {
        private FormManagementModelBuilderConfigurationOptions options;
        public ShortTextConfiguration(FormManagementModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<ShortText> builder)
        {
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<ShortText> builder);

        #endregion
    }

}
