//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.Cms.Routes
{
    [Area("cms")]
    [RemoteService(true)]
    [ControllerName("FS.Cms.Routes(cms)")]
    [Route("api/cms/routes")]
    public partial class RoutesApi : CmsController , IRoutesApi //auto-generated
    {

    }
}
