//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Data;

namespace FS.Cms.Posts
{
    public partial class Post : 
        Volo.Abp.Domain.Entities.Auditing.FullAuditedAggregateRoot<Guid>,
        Volo.Abp.MultiTenancy.IMultiTenant
    {

        public Post()
        {
            this.PostTags = new List<PostTagMap>();
            OnCreated();
        }

        public virtual System.Guid BlogId
        {
            get;
            set;
        }

        public virtual string Title
        {
            get;
            set;
        }

        public virtual string Subtitle
        {
            get;
            set;
        }

        public virtual int Sequence
        {
            get;
            set;
        }

        public virtual string LinkUrl
        {
            get;
            set;
        }

        public virtual bool Disable
        {
            get;
            set;
        }

        public virtual System.DateTime StartTime
        {
            get;
            set;
        }

        public virtual System.DateTime? EndTime
        {
            get;
            set;
        }

        public virtual DisplayMode DisplayMode
        {
            get;
            set;
        }
        public virtual List<FS.Cms.Core.Resource> Contents 
        {

            get
            {
                return this.GetExtraProperty<List<FS.Cms.Core.Resource>>(nameof(Contents));
            }
            set
            {
                this.SetProperty(nameof(Contents), value);
            }
        } 
        public virtual List<FS.Cms.Core.Resource> Attachments 
        {

            get
            {
                return this.GetExtraProperty<List<FS.Cms.Core.Resource>>(nameof(Attachments));
            }
            set
            {
                this.SetProperty(nameof(Attachments), value);
            }
        } 
        public virtual List<FS.Cms.Core.Resource> Images 
        {

            get
            {
                return this.GetExtraProperty<List<FS.Cms.Core.Resource>>(nameof(Images));
            }
            set
            {
                this.SetProperty(nameof(Images), value);
            }
        } 

        public virtual System.Guid? TenantId
        {
            get;
            set;
        }

        public virtual IList<PostTagMap> PostTags
        {
            get;
            set;
        }


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
