//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.Theme.Banners
{
    public partial class BannersApi : IBannersApi // pls write here
    {
    }
}
