//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.3.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.CmsKitManagement.Blogs.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKitManagement.Blogs
{
    public partial class BlogsApi //: IPostRouteCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("post-route/id")]
        [NonAction][RemoteService(false)]
        public Task<PostRouteWithDetailsDto> GetAsync([FromQuery] PostRoutePrimaryKeyDto PostRoutePrimaryKey)
        {
            return this.PostRouteCrudAppService.GetAsync(PostRoutePrimaryKey);
        }

        [HttpGet]
        [Route("post-route")]
        [RemoteService(true)]
        public Task<PagedResultDto<PostRouteWithDetailsDto>> GetListAsync(PostRouteGetListDto PostRouteGetList)
        {
            return this.PostRouteCrudAppService.GetListAsync(PostRouteGetList);
        }

        [HttpPost]
        [Route("post-route")]
        [NonAction][RemoteService(false)]
        public Task<PostRouteWithDetailsDto> CreateAsync(PostRouteCreateDto PostRouteCreate)
        {
            return this.PostRouteCrudAppService.CreateAsync(PostRouteCreate);
        }

        [HttpPut]
        [Route("post-route/id")]
        [NonAction][RemoteService(false)]
        public Task<PostRouteWithDetailsDto> UpdateAsync([FromQuery] PostRoutePrimaryKeyDto PostRoutePrimaryKey, PostRouteUpdateDto PostRouteUpdate)
        {
            return this.PostRouteCrudAppService.UpdateAsync(PostRoutePrimaryKey,PostRouteUpdate);
        }

        [HttpDelete]
        [Route("post-route/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] PostRoutePrimaryKeyDto PostRoutePrimaryKey)
        {
            return this.PostRouteCrudAppService.DeleteAsync(PostRoutePrimaryKey);
        }
    }
}
