//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Entity.EntityDefaults
{
    public partial class EntityDefaultCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<FS.Entity.EntityDefaults.EntityDefault, FS.Entity.EntityDefaults.Dtos.EntityDefaultWithDetailsDto, Guid, FS.Entity.EntityDefaults.Dtos.EntityDefaultGetListDto, FS.Entity.EntityDefaults.Dtos.EntityDefaultCreateDto, FS.Entity.EntityDefaults.Dtos.EntityDefaultUpdateDto>,
        IEntityDefaultCrudAppService
    {
        private readonly IEntityDefaultRepository _repository;

        public EntityDefaultCrudAppService(IEntityDefaultRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
