//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using JetBrains.Annotations;

namespace FS.Wbm.EntityFrameworkCore
{
    public partial class WbmModelBuilderConfigurationOptions : Volo.Abp.EntityFrameworkCore.Modeling.AbpModelBuilderConfigurationOptions
    {
        public WbmModelBuilderConfigurationOptions(
            [NotNull] string tablePrefix = "",
            [CanBeNull] string schema = null)
            : base(
                tablePrefix,
                schema)
        {

        }
    }
}
