//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.FormManagement.Localization;

namespace FS.FormManagement.Records
{
    public class RecordsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var RecordsGroup = context.AddGroup(RecordsPermissionNames.ModuleName,L(RecordsPermissionNames.ModuleName));

            var Record = RecordsGroup.AddPermission(RecordsPermissionNames.Record.Default,L(RecordsPermissionNames.Record.Default));
            Record.AddChild(RecordsPermissionNames.Record.Create , L("DisplayName:Record.Create"));
            Record.AddChild(RecordsPermissionNames.Record.Update , L("DisplayName:Record.Update"));
            Record.AddChild(RecordsPermissionNames.Record.Delete , L("DisplayName:Record.Delete"));

            var RecordItem = RecordsGroup.AddPermission(RecordsPermissionNames.RecordItem.Default,L(RecordsPermissionNames.RecordItem.Default));
            RecordItem.AddChild(RecordsPermissionNames.RecordItem.Create , L("DisplayName:RecordItem.Create"));
            RecordItem.AddChild(RecordsPermissionNames.RecordItem.Update , L("DisplayName:RecordItem.Update"));
            RecordItem.AddChild(RecordsPermissionNames.RecordItem.Delete , L("DisplayName:RecordItem.Delete"));

        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<FormManagementResource>(name);
        }
    }
}
