module.exports = {
  projects: [
    '<rootDir>/apps/dev-app',
    '<rootDir>/libs/account',
    '<rootDir>/libs/emailing',
    '<rootDir>/libs/theme/alain',
    '<rootDir>/libs/theme-alain',
    '<rootDir>/apps/alain-app',
    '<rootDir>/libs/theme-alain-ms',
    '<rootDir>/apps/alain-ms-app',
    '<rootDir>/libs/crm',
    '<rootDir>/libs/cms',
    '<rootDir>/libs/theme-core',
    '<rootDir>/libs/theme-the-project',
    '<rootDir>/apps/iic-public-app',
    '<rootDir>/apps/iic-admin-app',
    '<rootDir>/apps/gfla-admin-app',
    '<rootDir>/libs/appt',
    '<rootDir>/apps/unify-app',
    '<rootDir>/libs/theme-unify',
  ],
};
