//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;
using FS.Coding.Codes.EntityFrameworkCore;

namespace FS.Coding.Codes.EntityFrameworkCore
{
    public partial class EfCoreCodingTreeRepository : 
        EasyAbp.Abp.Trees.EfCoreTreeRepository<ICodesDbContext,FS.Coding.Codes.Coding>,
        ICodingTreeRepository
    {
        public EfCoreCodingTreeRepository(IDbContextProvider<ICodesDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<FS.Coding.Codes.Coding>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
}
