//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace FS.FormManagement.Documents
{
    public static class DocumentsQueryableExtensions //auto-generated
    {
        public static IQueryable<Version> IncludeDetails(this IQueryable<Version> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.DocumentDefinition);
        }
        public static IQueryable<DocumentDefinition> IncludeDetails(this IQueryable<DocumentDefinition> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.CurrentVersion);
        }
    }
}
