//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
//------------------------------------------------------------------------------
using FS.Cms.Posts.Dtos;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;

namespace FS.Cms.Posts
{
    public partial class PostsApi : IPostsApi
    {

        [HttpGet]
        [Route("with-tag/{id}")]
        public async Task<PostWithTagsDto> GetWithTags(Guid id)
        {
            return null;
            //return await this.PostCrudAppService.GetWithTags(id);
        }

        [HttpGet]
        [Route("get-list-with-tag")]        
        public async Task<PagedResultDto<PostWithTagsDto>> GetListWithTagAsync(PostGetListDto input)
        {
            return null;
            //return await this.PostCrudAppService.GetListWithTagAsync(input);
        }
    }
}
