//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.Cms.Blogs
{
    [Area("cms")]
    [RemoteService(true)]
    [ControllerName("FS.Cms.Blogs(cms)")]
    [Route("api/cms/blogs")]
    public partial class BlogsApi : CmsController , IBlogsApi //auto-generated
    {

        protected IBlogCrudAppService BlogCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IBlogCrudAppService>();

        [HttpOptions]
        public Dtos.MetaData Options()
        {
            return new Dtos.MetaData();
        }
    }
}
