//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.Entity.EntityDefaults.Dtos
{

    public partial class EntityDefaultDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual string DefaultType { get; set; }

    }

    public partial class EntityDefaultCreateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual string DefaultType { get; set; }

    }

    public partial class EntityDefaultUpdateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual string DefaultType { get; set; }

    }

    public partial class EntityDefaultGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class EntityDefaultWithDetailsDto : EntityDefaultDto
    {
        public List<EntityDefaultItemDto> EntityItems { get; set; }

    }
}
