//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Theme.WebSites
{
    public partial class WebSiteDefinitionCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.Theme.WebSites.WebSiteDefinition, FS.Theme.WebSites.Dtos.WebSiteDefinitionWithDetailsDto, FS.Theme.WebSites.Dtos.WebSiteDefinitionPrimaryKeyDto, Guid, FS.Theme.WebSites.Dtos.WebSiteDefinitionGetListDto, FS.Theme.WebSites.Dtos.WebSiteDefinitionCreateDto, FS.Theme.WebSites.Dtos.WebSiteDefinitionUpdateDto>,
        IWebSiteDefinitionCrudAppService
    {
        private readonly IWebSiteDefinitionRepository _repository;

        public WebSiteDefinitionCrudAppService(IWebSiteDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
