//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Data;

namespace FS.Theme.Banners
{
    public partial class Banner : 
        Volo.Abp.Domain.Entities.Auditing.AuditedAggregateRoot<Guid>,
        Volo.Abp.MultiTenancy.IMultiTenant
    {

        public Banner()
        {
            this.Enable = true;
            OnCreated();
        }

        public Banner(System.Guid id) : this()
        {
            this.Id = id;
        }

        public virtual string No
        {
            get;
            set;
        }

        public virtual string DisplayName
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual bool Enable
        {
            get;
            set;
        }
        public virtual FS.Theme.Banners.BannerConfig BannerConfig 
        {

            get
            {
                return this.GetExtraProperty<FS.Theme.Banners.BannerConfig>(nameof(BannerConfig));
            }
            set
            {
                this.SetExtraProperty(nameof(BannerConfig), value);
            }
        } 

        public virtual System.Guid BannerDefinitionId
        {
            get;
            set;
        }

        public virtual System.Guid? TenantId
        {
            get;
            set;
        }

        public virtual BannerDefinition BannerDefinition
        {
            get;
            set;
        }


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
