//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.CmsKitManagement.Contents.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKitManagement.Contents
{
    public partial class ContentsApi //: IEntityContentDefinitionCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("entity-content-definition/id")]
        [NonAction][RemoteService(false)]
        public Task<EntityContentDefinitionWithDetailsDto> GetAsync([FromQuery] EntityContentDefinitionPrimaryKeyDto EntityContentDefinitionPrimaryKey)
        {
            return this.EntityContentDefinitionCrudAppService.GetAsync(EntityContentDefinitionPrimaryKey);
        }

        [HttpGet]
        [Route("entity-content-definition")]
        [RemoteService(true)]
        public Task<PagedResultDto<EntityContentDefinitionWithDetailsDto>> GetListAsync(EntityContentDefinitionGetListDto EntityContentDefinition)
        {
            return this.EntityContentDefinitionCrudAppService.GetListAsync(EntityContentDefinition);
        }

        [HttpPost]
        [Route("entity-content-definition")]
        [NonAction][RemoteService(false)]
        public Task<EntityContentDefinitionWithDetailsDto> CreateAsync(EntityContentDefinitionCreateDto EntityContentDefinition)
        {
            return this.EntityContentDefinitionCrudAppService.CreateAsync(EntityContentDefinition);
        }

        [HttpPut]
        [Route("entity-content-definition/id")]
        [NonAction][RemoteService(false)]
        public Task<EntityContentDefinitionWithDetailsDto> UpdateAsync([FromQuery] EntityContentDefinitionPrimaryKeyDto EntityContentDefinitionPrimaryKey, EntityContentDefinitionUpdateDto EntityContentDefinition)
        {
            return this.EntityContentDefinitionCrudAppService.UpdateAsync(EntityContentDefinitionPrimaryKey,EntityContentDefinition);
        }

        [HttpDelete]
        [Route("entity-content-definition/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] EntityContentDefinitionPrimaryKeyDto EntityContentDefinitionPrimaryKey)
        {
            return this.EntityContentDefinitionCrudAppService.DeleteAsync(EntityContentDefinitionPrimaryKey);
        }
    }
}
