//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.FormManagement.Records
{
    public partial interface IRecordsStore : IDomainService //auto-generated
    {
        IRecordRepository Record { get; }
        IRecordItemRepository RecordItem { get; }
    }
    public partial class RecordsStore : DomainService, IRecordsStore //auto-generated
    {
        public IRecordRepository Record => this.LazyServiceProvider.LazyGetRequiredService<IRecordRepository>();
        public IRecordItemRepository RecordItem => this.LazyServiceProvider.LazyGetRequiredService<IRecordItemRepository>();
    }
}
