//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using FS.Coding.Codes.EntityFrameworkCore;
using FS.Coding.SerialNumbers.EntityFrameworkCore;


namespace FS.CodingManagement.EntityFrameworkCore
{
    public static partial class CodingManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureCodingManagement(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ConfigureCodes();
            builder.ConfigureSerialNumbers();

        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
