//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Volo.Abp.DependencyInjection;

namespace FS.CodingManagement.EntityFrameworkCore
{
    [ConnectionStringName(CodingManagementDbProperties.ConnectionStringName)]
    public partial interface ICodingManagementDbContext : IEfCoreDbContext,
        FS.Coding.Codes.EntityFrameworkCore.ICodesDbContext,
        FS.Coding.SerialNumbers.EntityFrameworkCore.ISerialNumbersDbContext
    {
        //DbSet<FS.Coding.Codes.Coding> Codings { get; set; }
        //DbSet<FS.Coding.SerialNumbers.SerialNumber> SerialNumbers { get; set; }
    }
}
