//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Linq.Expressions;

namespace FS.Cms.Posts
{
    public partial class EfCorePostTagRepository : 
        EfCoreRepository<FS.Cms.EntityFrameworkCore.ICmsDbContext,FS.Cms.Posts.PostTag,Guid>,
        IPostTagRepository
    {
        public EfCorePostTagRepository(IDbContextProvider<FS.Cms.EntityFrameworkCore.ICmsDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override IQueryable<FS.Cms.Posts.PostTag> WithDetails()
        {
            return base.WithDetails(new Expression<Func<FS.Cms.Posts.PostTag, object>>[] 
            {
                x => x.Post,
                x => x.Tag
            });
        }
    }
}
