//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.Cms.EntityFrameworkCore;

namespace FS.Cms.Posts
{
    public partial class PostTagMapConfiguration : IEntityTypeConfiguration<PostTagMap>
    {
        private CmsModelBuilderConfigurationOptions options;
        public PostTagMapConfiguration(CmsModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<PostTagMap> builder)
        {
            builder.ToTable(options.TablePrefix + @"PostTagMaps", options.Schema);
            builder.Property<System.Guid>(x => x.PostId).HasColumnName(@"PostId").ValueGeneratedNever();
            builder.Property<System.Guid>(x => x.TagCodeId).HasColumnName(@"TagCodeId").ValueGeneratedNever();
            builder.Property<System.Guid?>(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.Post).WithMany().IsRequired(true).HasForeignKey(@"PostId");

            builder.ConfigureFullAuditedAggregateRoot();

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<PostTagMap> builder);

        #endregion
    }

}
