//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Coding.Codes
{
    public partial class CodingCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.Coding.Codes.Coding, 
            FS.Coding.Codes.Dtos.CodingWithDetailsDto, 
            FS.Coding.Codes.Dtos.CodingDto, 
            Guid, 
            FS.Coding.Codes.Dtos.CodingGetListDto, 
            FS.Coding.Codes.Dtos.CodingCreateDto, 
            FS.Coding.Codes.Dtos.CodingUpdateDto>,
        ICodingCrudAppService
    {
        private readonly ICodingTreeRepository _repository;

        public CodingCrudAppService(ICodingTreeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
