//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FS.Theme.Routes
{
    public partial interface IRoutesAppService : Volo.Abp.Application.Services.IApplicationService // pls write here
    {
    }
}
