// import { DEFAULT_WEBSITEDEFINITION_CREATE_FORM_PROPS } from './default-websitedefinition-create-form-props';

// export const DEFAULT_WEBSITEDEFINITION_EDIT_FORM_PROPS = DEFAULT_WEBSITEDEFINITION_CREATE_FORM_PROPS;
