//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;

namespace FS.Cms.Documents
{
    [Area("cms")]
    [RemoteService(true)]
    [ControllerName("Documents Api")]
    [Route("api/cms/documents")]
    public partial class DocumentsApi : CmsController //auto-generated IDocumentsApi
    {
        IDocumentsAppService _DocumentsAppService;
        protected IDocumentsAppService DocumentsAppService => this.LazyGetRequiredService(ref _DocumentsAppService);

        IDocumentDefinitionCrudAppService _DocumentDefinitionCrudAppService;
        protected IDocumentDefinitionCrudAppService DocumentDefinitionCrudAppService => this.LazyGetRequiredService(ref _DocumentDefinitionCrudAppService);

        IDocumentCrudAppService _DocumentCrudAppService;
        protected IDocumentCrudAppService DocumentCrudAppService => this.LazyGetRequiredService(ref _DocumentCrudAppService);


    }
}
