//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.Cms.Documents.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.Cms.Documents
{
    public partial class DocumentsApi : IDocumentCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("document/id")]
        [RemoteService(false)]
        public Task<DocumentWithDetailsDto> GetAsync([FromQuery] DocumentPrimaryKeyDto DocumentPrimaryKey)
        {
            return this.DocumentCrudAppService.GetAsync(DocumentPrimaryKey);
        }

        [HttpGet]
        [Route("document")]
        [RemoteService(false)]
        public Task<PagedResultDto<DocumentWithDetailsDto>> GetListAsync(DocumentGetListDto DocumentGetList)
        {
            return this.DocumentCrudAppService.GetListAsync(DocumentGetList);
        }

        [HttpPost]
        [Route("document")]
        [RemoteService(false)]
        public Task<DocumentWithDetailsDto> CreateAsync(DocumentCreateDto DocumentCreate)
        {
            return this.DocumentCrudAppService.CreateAsync(DocumentCreate);
        }

        [HttpPut]
        [Route("document/id")]
        [RemoteService(false)]
        public Task<DocumentWithDetailsDto> UpdateAsync([FromQuery] DocumentPrimaryKeyDto DocumentPrimaryKey, DocumentUpdateDto DocumentUpdate)
        {
            return this.DocumentCrudAppService.UpdateAsync(DocumentPrimaryKey,DocumentUpdate);
        }

        [HttpDelete]
        [Route("document/id")]
        [RemoteService(false)]
        public Task DeleteAsync([FromQuery] DocumentPrimaryKeyDto DocumentPrimaryKey)
        {
            return this.DocumentCrudAppService.DeleteAsync(DocumentPrimaryKey);
        }
    }
}
