//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 2.0.0
//
//------------------------------------------------------------------------------
using FS.Cms.Documents.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.Cms.Documents
{
    public partial class DocumentsApi : IDocumentCrudAppService //auto-generated
    {
        [HttpGet]
        [Route("document/id")]
        [RemoteService(false)]
        public Task<DocumentWithDetailsDto> GetAsync([FromQuery] DocumentPrimaryKeyDto key)
        {
            return this.DocumentCrudAppService.GetAsync(key);
        }

        [HttpGet]
        [Route("document")]
        [RemoteService(false)]
        public Task<PagedResultDto<DocumentWithDetailsDto>> GetListAsync(DocumentGetListDto input)
        {
            return this.DocumentCrudAppService.GetListAsync(input);
        }

        [HttpPost]
        [Route("document")]
        [RemoteService(false)]
        public Task<DocumentWithDetailsDto> CreateAsync(DocumentCreateDto input)
        {
            return this.DocumentCrudAppService.CreateAsync(input);
        }

        [HttpPut]
        [Route("document/id")]
        [RemoteService(false)]
        public Task<DocumentWithDetailsDto> UpdateAsync([FromQuery] DocumentPrimaryKeyDto key, DocumentUpdateDto input)
        {
            return this.DocumentCrudAppService.UpdateAsync(key,input);
        }

        [HttpDelete]
        [Route("document/id")]
        [RemoteService(false)]
        public Task DeleteAsync([FromQuery] DocumentPrimaryKeyDto key)
        {
            return this.DocumentCrudAppService.DeleteAsync(key);
        }
    }
}
