//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace FS.CodingManagement.Codes
{
    public static class CodesQueryableExtensions //auto-generated
    {
        public static IQueryable<Coding> IncludeDetails(this IQueryable<Coding> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.Children)
                .Include(x => x.Parent);
        }
    }
}
