//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 4.4.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;

namespace FS.CodingManagement.Codes
{
    public partial class EfCoreCodingTreeRepository : 
        EasyAbp.Abp.Trees.EfCoreTreeRepository<FS.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext,FS.CodingManagement.Codes.Coding>,
        ICodingTreeRepository
    {
        public EfCoreCodingTreeRepository(IDbContextProvider<FS.CodingManagement.EntityFrameworkCore.ICodingManagementDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<FS.CodingManagement.Codes.Coding>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
}
