//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.FormManagement.FormResponses.Dtos
{
    public partial class MetaData
    {
        public AnswerPrimaryKeyDto AnswerPrimaryKeyDto => new AnswerPrimaryKeyDto();
        public AnswerDto AnswerDto => new AnswerDto();
        public AnswerCreateDto AnswerCreateDto => new AnswerCreateDto();
        public AnswerUpdateDto AnswerUpdateDto => new AnswerUpdateDto();
        public AnswerGetListDto AnswerGetListDto => new AnswerGetListDto();
        public AnswerWithDetailsDto AnswerWithDetailsDto => new AnswerWithDetailsDto();
    }

    public partial class AnswerPrimaryKeyDto : EntityDto<Guid>
    {
    }

    public partial class AnswerDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Value { get; set; }

        public virtual System.Guid FormResponseId { get; set; }

        public virtual System.Guid QuestionId { get; set; }

        public virtual System.Guid? ChoiceId { get; set; }

        public virtual System.DateTime AnswerDate { get; set; }

    }

    public partial class AnswerCreateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual string Value { get; set; }

        public virtual System.Guid FormResponseId { get; set; }

        public virtual System.Guid QuestionId { get; set; }

        public virtual System.Guid? ChoiceId { get; set; }

        public virtual System.DateTime AnswerDate { get; set; }

    }

    public partial class AnswerUpdateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual string Value { get; set; }

        public virtual System.Guid FormResponseId { get; set; }

        public virtual System.Guid QuestionId { get; set; }

        public virtual System.Guid? ChoiceId { get; set; }

        public virtual System.DateTime AnswerDate { get; set; }

    }

    public partial class AnswerGetListDto : SearchResultRequestDto
    {
    }

    public partial class AnswerWithDetailsDto : AnswerDto
    {
        public FormResponseDto Record { get; set; }

    }
}
