//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.FormManagement.FormResponses.Dtos
{
    public partial class MetaData
    {
        public FormResponsePrimaryKeyDto FormResponsePrimaryKeyDto => new FormResponsePrimaryKeyDto();
        public FormResponseDto FormResponseDto => new FormResponseDto();
        public FormResponseCreateDto FormResponseCreateDto => new FormResponseCreateDto();
        public FormResponseUpdateDto FormResponseUpdateDto => new FormResponseUpdateDto();
        public FormResponseGetListDto FormResponseGetListDto => new FormResponseGetListDto();
        public FormResponseWithDetailsDto FormResponseWithDetailsDto => new FormResponseWithDetailsDto();
    }

    public partial class FormResponsePrimaryKeyDto : EntityDto<Guid>
    {
    }

    public partial class FormResponseDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual System.Guid FormId { get; set; }

        public virtual System.Guid? UserId { get; set; }

        public virtual string Email { get; set; }

    }

    public partial class FormResponseCreateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual System.Guid FormId { get; set; }

        public virtual System.Guid? UserId { get; set; }

        public virtual string Email { get; set; }

    }

    public partial class FormResponseUpdateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual System.Guid FormId { get; set; }

        public virtual System.Guid? UserId { get; set; }

        public virtual string Email { get; set; }

    }

    public partial class FormResponseGetListDto : SearchResultRequestDto
    {
    }

    public partial class FormResponseWithDetailsDto : FormResponseDto
    {
        public List<AnswerDto> Answers { get; set; }

    }
}
