//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Cms.Posts
{
    public partial interface IPostAttachmentFilesCrudAppService : 
        FS.Abp.Application.Services.ICrudAppService<FS.Cms.Posts.Dtos.PostAttachmentFilesWithDetailsDto, Guid, FS.Cms.Posts.Dtos.PostAttachmentFilesGetListInput, FS.Cms.Posts.Dtos.PostAttachmentFilesCreateInput, FS.Cms.Posts.Dtos.PostAttachmentFilesUpdateInput>
    {

    }
}
