//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating CrudApplication.
// 1.102.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Cms.Posts
{
    public partial interface IPostTagMapCrudAppService : 
        FS.Abp.Application.Services.ICrudAppService<FS.Cms.Posts.Dtos.PostTagMapWithDetailsDto, Guid, FS.Cms.Posts.Dtos.PostTagMapGetListInput, FS.Cms.Posts.Dtos.PostTagMapCreateInput, FS.Cms.Posts.Dtos.PostTagMapUpdateInput>
    {

    }
}
