//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Entity.EntityDefaults.Dtos
{
    public partial class EntityPropertyAutoMapperProfile : Profile
    {
        public EntityPropertyAutoMapperProfile()
        {
            CreateMap<FS.Entity.EntityDefaults.EntityProperty, EntityPropertyDto>()
            .ReverseMap();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
