//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 1.102.0.0
//
//------------------------------------------------------------------------------
using FS.Cms.Posts.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.Cms.Posts
{
    public partial class PostsApi : IPostCrudAppService //auto-generated
    {
        [HttpGet]
        [Route("post/id")]
        [RemoteService(true)]
        public Task<PostWithDetailsDto> GetAsync([FromQuery] PostPrimaryKeyDto key)
        {
            return this.PostCrudAppService.GetAsync(key);
        }

        [HttpGet]
        [Route("post")]
        [RemoteService(true)]
        public Task<PagedResultDto<PostWithDetailsDto>> GetListAsync(PostGetListDto input)
        {
            return this.PostCrudAppService.GetListAsync(input);
        }

        [HttpPost]
        [Route("post")]
        [RemoteService(true)]
        public Task<PostWithDetailsDto> CreateAsync(PostCreateDto input)
        {
            return this.PostCrudAppService.CreateAsync(input);
        }

        [HttpPut]
        [Route("post/id")]
        [RemoteService(true)]
        public Task<PostWithDetailsDto> UpdateAsync([FromQuery] PostPrimaryKeyDto key, PostUpdateDto input)
        {
            return this.PostCrudAppService.UpdateAsync(key,input);
        }

        [HttpDelete]
        [Route("post/id")]
        [RemoteService(true)]
        public Task DeleteAsync([FromQuery] PostPrimaryKeyDto key)
        {
            return this.PostCrudAppService.DeleteAsync(key);
        }
    }
}
