//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.Versions.Dtos
{
    public partial class VersionDefinitionAutoMapperProfile : Profile
    {
        public VersionDefinitionAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.Versions.VersionDefinition, VersionDefinitionDto>()
            .ReverseMap();
        
            CreateMap<VersionDefinitionCreateDto, FS.FormManagement.Versions.VersionDefinition>();
        
            CreateMap<VersionDefinitionUpdateDto, FS.FormManagement.Versions.VersionDefinition>();
        
            CreateMap<FS.FormManagement.Versions.VersionDefinition, VersionDefinitionWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
