//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.Theme.WebSites
{
    [Area("theme")]
    [RemoteService(true)]
    [ControllerName("FS.Theme.WebSites(theme)")]
    [Route("api/theme/web-sites")]
    public partial class WebSitesApi : ThemeController , IWebSitesApi //auto-generated
    {

        protected IWebSiteDefinitionCrudAppService WebSiteDefinitionCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IWebSiteDefinitionCrudAppService>();

        [HttpOptions]
        public Dtos.MetaData Options()
        {
            return new Dtos.MetaData();
        }
    }
}
