//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.Wbm.Core
{
    public partial class 過磅記錄CrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.Wbm.Core.過磅記錄, FS.Wbm.Core.Dtos.過磅記錄WithDetailsDto, FS.Wbm.Core.Dtos.過磅記錄PrimaryKeyDto, Int64, FS.Wbm.Core.Dtos.過磅記錄GetListDto, FS.Wbm.Core.Dtos.過磅記錄CreateDto, FS.Wbm.Core.Dtos.過磅記錄UpdateDto>,
        I過磅記錄CrudAppService
    {
        private readonly I過磅記錄Repository _repository;

        public 過磅記錄CrudAppService(I過磅記錄Repository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
