//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.FormResponses.Dtos
{
    public partial class AnswerAutoMapperProfile : Profile
    {
        public AnswerAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.FormResponses.Answer, AnswerDto>()
            .ReverseMap();
        
            CreateMap<AnswerCreateDto, FS.FormManagement.FormResponses.Answer>();
        
            CreateMap<AnswerUpdateDto, FS.FormManagement.FormResponses.Answer>();
        
            CreateMap<FS.FormManagement.FormResponses.Answer, AnswerWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
