//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.FormManagement.FormResponses.Dtos
{
    public partial class FormResponseAutoMapperProfile : Profile
    {
        public FormResponseAutoMapperProfile()
        {
            CreateMap<FS.FormManagement.FormResponses.FormResponse, FormResponseDto>()
            .ReverseMap();
        
            CreateMap<FormResponseCreateDto, FS.FormManagement.FormResponses.FormResponse>();
        
            CreateMap<FormResponseUpdateDto, FS.FormManagement.FormResponses.FormResponse>();
        
            CreateMap<FS.FormManagement.FormResponses.FormResponse, FormResponseWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
