import { DEFAULT_BANNERDEFINITION_CREATE_FORM_PROPS } from './default-bannerdefinition-create-form-props';

export const DEFAULT_BANNERDEFINITION_EDIT_FORM_PROPS = DEFAULT_BANNERDEFINITION_CREATE_FORM_PROPS;
