//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.Forms
{
    public partial class ChoiceCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.FormManagement.Forms.Choice, FS.FormManagement.Forms.Dtos.ChoiceWithDetailsDto, FS.FormManagement.Forms.Dtos.ChoicePrimaryKeyDto, Guid, FS.FormManagement.Forms.Dtos.ChoiceGetListDto, FS.FormManagement.Forms.Dtos.ChoiceCreateDto, FS.FormManagement.Forms.Dtos.ChoiceUpdateDto>,
        IChoiceCrudAppService
    {
        private readonly IChoiceRepository _repository;

        public ChoiceCrudAppService(IChoiceRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
