//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.Forms
{
    public partial class QuestionCrudAppService :  // auto-generated
        FS.Abp.Application.Services.EntityWithKeyCrudAppService<FS.FormManagement.Forms.Question, FS.FormManagement.Forms.Dtos.QuestionWithDetailsDto, FS.FormManagement.Forms.Dtos.QuestionPrimaryKeyDto, Guid, FS.FormManagement.Forms.Dtos.QuestionGetListDto, FS.FormManagement.Forms.Dtos.QuestionCreateDto, FS.FormManagement.Forms.Dtos.QuestionUpdateDto>,
        IQuestionCrudAppService
    {
        private readonly IQuestionRepository _repository;

        public QuestionCrudAppService(IQuestionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
