//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Cms.Documents.Dtos
{
    public partial class MetaData
    {
        public DocumentPrimaryKeyDto DocumentPrimaryKeyDto => new DocumentPrimaryKeyDto();
        public DocumentDto DocumentDto => new DocumentDto();
        public DocumentCreateDto DocumentCreateDto => new DocumentCreateDto();
        public DocumentUpdateDto DocumentUpdateDto => new DocumentUpdateDto();
        public DocumentGetListDto DocumentGetListDto => new DocumentGetListDto();
        public DocumentWithDetailsDto DocumentWithDetailsDto => new DocumentWithDetailsDto();
    }

    public partial class DocumentPrimaryKeyDto : EntityDto<Guid>
    {
    }

    public partial class DocumentDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Content { get; set; }

        public virtual string DocumentDefinitionId { get; set; }

        public virtual string Code { get; set; }

        public virtual System.Guid? ParentId { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual int Level { get; set; }

    }

    public partial class DocumentCreateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual string Content { get; set; }

        public virtual string DocumentDefinitionId { get; set; }

        public virtual string Code { get; set; }

        public virtual System.Guid? ParentId { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual int Level { get; set; }

    }

    public partial class DocumentUpdateDto : Volo.Abp.ObjectExtending.ExtensibleObject
    {
        public virtual string Content { get; set; }

        public virtual string DocumentDefinitionId { get; set; }

        public virtual string Code { get; set; }

        public virtual System.Guid? ParentId { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual int Level { get; set; }

    }

    public partial class DocumentGetListDto : SearchResultRequestDto
    {
    }

    public partial class DocumentWithDetailsDto : DocumentDto
    {
        public DocumentDefinitionDto DocumentDefinition { get; set; }

        public List<DocumentDto> Children { get; set; }

        public DocumentDto Parent { get; set; }

    }
}
