//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.Cms.Core
{
    public partial class CoreApi : ICoreApi // pls write here
    {
    }
}
