//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Cms.Core.Dtos
{
    public partial class BlogDefinitionSettingDto
    {
        public string ListStyle { get; set; }

        public int Sequence { get; set; }

        public string Url { get; set; }

        public string IconUrl { get; set; }

    }
    public partial class BlogDefinitionSettingWithDetailsDto : BlogDefinitionSettingDto
    {
    }
}
