//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 2.0.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Cms.Core.Dtos
{
    public partial class CmsFileFieldDto
    {
        public string Title { get; set; }

        public string Url { get; set; }

        public string Size { get; set; }

    }
    public partial class CmsFileFieldWithDetailsDto : CmsFileFieldDto
    {
    }
}
