//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.MultiLinguals
{
    public partial interface IMultiLingualCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.CmsKitManagement.MultiLinguals.Dtos.MultiLingualWithDetailsDto, FS.CmsKitManagement.MultiLinguals.Dtos.MultiLingualPrimaryKeyDto, FS.CmsKitManagement.MultiLinguals.Dtos.MultiLingualGetListDto, FS.CmsKitManagement.MultiLinguals.Dtos.MultiLingualCreateDto, FS.CmsKitManagement.MultiLinguals.Dtos.MultiLingualUpdateDto>
    {

    }
}
