//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.Theme.Banners.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.Theme.Banners
{
    public partial class BannersApi //: IBannerCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("banner/id")]
        [NonAction][RemoteService(false)]
        public Task<BannerWithDetailsDto> GetAsync([FromQuery] BannerPrimaryKeyDto BannerPrimaryKey)
        {
            return this.BannerCrudAppService.GetAsync(BannerPrimaryKey);
        }

        [HttpGet]
        [Route("banner")]
        [RemoteService(true)]
        public Task<PagedResultDto<BannerWithDetailsDto>> GetListAsync(BannerGetListDto BannerGetList)
        {
            return this.BannerCrudAppService.GetListAsync(BannerGetList);
        }

        [HttpPost]
        [Route("banner")]
        [NonAction][RemoteService(false)]
        public Task<BannerWithDetailsDto> CreateAsync(BannerCreateDto BannerCreate)
        {
            return this.BannerCrudAppService.CreateAsync(BannerCreate);
        }

        [HttpPut]
        [Route("banner/id")]
        [NonAction][RemoteService(false)]
        public Task<BannerWithDetailsDto> UpdateAsync([FromQuery] BannerPrimaryKeyDto BannerPrimaryKey, BannerUpdateDto BannerUpdate)
        {
            return this.BannerCrudAppService.UpdateAsync(BannerPrimaryKey,BannerUpdate);
        }

        [HttpDelete]
        [Route("banner/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] BannerPrimaryKeyDto BannerPrimaryKey)
        {
            return this.BannerCrudAppService.DeleteAsync(BannerPrimaryKey);
        }
    }
}
