//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.EntityFrameworkCore;

namespace FS.Customers
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        private FSModelBuilderConfigurationOptions options;
        public PersonConfiguration(FSModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<Person> builder)
        {
            builder.Property<string>(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<Person> builder);

        #endregion
    }

}
