//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using FS.FormManagement.FormResponses.Dtos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace FS.FormManagement.FormResponses
{
    public partial class FormResponsesApi //: IAnswerCrudAppService //auto-generated 
    {
        [HttpGet]
        [Route("answer/id")]
        [NonAction][RemoteService(false)]
        public Task<AnswerWithDetailsDto> GetAsync([FromQuery] AnswerPrimaryKeyDto AnswerPrimaryKey)
        {
            return this.AnswerCrudAppService.GetAsync(AnswerPrimaryKey);
        }

        [HttpGet]
        [Route("answer")]
        [RemoteService(true)]
        public Task<PagedResultDto<AnswerWithDetailsDto>> GetListAsync(AnswerGetListDto AnswerGetList)
        {
            return this.AnswerCrudAppService.GetListAsync(AnswerGetList);
        }

        [HttpPost]
        [Route("answer")]
        [NonAction][RemoteService(false)]
        public Task<AnswerWithDetailsDto> CreateAsync(AnswerCreateDto AnswerCreate)
        {
            return this.AnswerCrudAppService.CreateAsync(AnswerCreate);
        }

        [HttpPut]
        [Route("answer/id")]
        [NonAction][RemoteService(false)]
        public Task<AnswerWithDetailsDto> UpdateAsync([FromQuery] AnswerPrimaryKeyDto AnswerPrimaryKey, AnswerUpdateDto AnswerUpdate)
        {
            return this.AnswerCrudAppService.UpdateAsync(AnswerPrimaryKey,AnswerUpdate);
        }

        [HttpDelete]
        [Route("answer/id")]
        [NonAction][RemoteService(false)]
        public Task DeleteAsync([FromQuery] AnswerPrimaryKeyDto AnswerPrimaryKey)
        {
            return this.AnswerCrudAppService.DeleteAsync(AnswerPrimaryKey);
        }
    }
}
