//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.2.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace FS.FormManagement.FormResponses
{
    [Area("form-management")]
    [RemoteService(true)]
    [ControllerName("FS.FormManagement.FormResponses(form-management)")]
    [Route("api/form-management/form-responses")]
    public partial class FormResponsesApi : FormManagementController , IFormResponsesApi //auto-generated
    {

        protected IFormResponseCrudAppService FormResponseCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IFormResponseCrudAppService>();

        protected IAnswerCrudAppService AnswerCrudAppService => this.LazyServiceProvider.LazyGetRequiredService<IAnswerCrudAppService>();

        [HttpOptions]
        public Dtos.MetaData Options()
        {
            return new Dtos.MetaData();
        }
    }
}
