//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using FS.Abp.Application.Dtos;

namespace FS.Theme.Banners.Dtos
{
    public partial class MetaData
    {
        public BannerConfigDto BannerConfigDto => new BannerConfigDto();
    }

    public partial class BannerConfigDto
    {
        public virtual string FileName { get; set; }

        public virtual string FileUrl { get; set; }

        public virtual int Sequence { get; set; }

    }
}
