//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 2.0.1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;
using FS.Cms.EntityFrameworkCore;

namespace FS.Cms.Documents
{
    public partial class DocumentConfiguration : IEntityTypeConfiguration<Document>
    {
        private CmsModelBuilderConfigurationOptions options;
        public DocumentConfiguration(CmsModelBuilderConfigurationOptions options)
        {
            this.options = options;
        }
        public void Configure(EntityTypeBuilder<Document> builder)
        {
            builder.ToTable(options.TablePrefix + @"Documents", options.Schema);
            builder.Property<string>(x => x.Content).HasColumnName(@"Content").IsRequired().ValueGeneratedNever();
            builder.Ignore(x => x.Files);
            builder.Property<string>(x => x.DocumentDefinitionId).HasColumnName(@"DocumentDefinitionId").ValueGeneratedNever();
            builder.Property<string>(x => x.Code).HasColumnName(@"Code").IsRequired().ValueGeneratedNever();
            builder.Property<System.Guid?>(x => x.ParentId).HasColumnName(@"ParentId").ValueGeneratedNever();
            builder.Property<string>(x => x.DisplayName).HasColumnName(@"DisplayName").IsRequired().ValueGeneratedNever();
            builder.Property<int>(x => x.Level).HasColumnName(@"Level").ValueGeneratedNever();
            builder.Property<System.Guid?>(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.DocumentDefinition).WithMany(op => op.Documents).IsRequired(true).HasForeignKey(@"DocumentDefinitionId");
            builder.HasMany(x => x.Children).WithOne(op => op.Parent).IsRequired(false).HasForeignKey(@"ParentId");
            builder.HasOne(x => x.Parent).WithMany(op => op.Children).IsRequired(false).HasForeignKey(@"ParentId");

            builder.ConfigureFullAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<Document> builder);

        #endregion
    }

}
